### ISSUE TITLE
Is there anyway to comment out the copyright at the end of the page?

### ISSUE THREAD

**Issue by bradagy** [rhazdon/hugo-theme-hello-friend-ng#101]
It would make my website look better if I could someone make it disappear. Thanks.

**Comment by TheGroundZero** [comment]
Have a look at `themes/hello-friend-ng/layouts/partials/footer.html`

Note that the [license](https://creativecommons.org/licenses/by-nc/4.0/) requires attribution.

**Comment by bradagy** [comment]
Understood. I appreciate the response.
