### ISSUE TITLE
Unwanted icons in code blocks

### ISSUE THREAD

**Issue by TheGroundZero** [rhazdon/hugo-theme-hello-friend-ng#104]
Hi

Is there an option to **not** replace text by icons, especially in code blocks?

For example, the following text was replaced by an icon, which is giving unwanted results.

``` bash
22/tcp open ssh   OpenSSH 7.9p1 Debian 10+deb10u1 (protocol 2.0)
| ssh-hostkey: 
|  2048 aa:99:a8:16:68:cd:41:cc:f9:6c:84:01:c7:59:09:5c (RSA)
|  256 93:dd:1a:23:ee:d7:1f:08:6b:58:47:09:73:a3:88:cc (ECDSA)
|_ 256 9d:d6:62:1e:7a:fb:8f:56:92:e6:37:f1:10:db:9b:ce (ED25519)
```

![image](https://user-images.githubusercontent.com/2406013/73556095-0843fd00-444f-11ea-9cba-0eb5a42df10a.png)

``` bash
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
```

![image](https://user-images.githubusercontent.com/2406013/73556214-45a88a80-444f-11ea-82ba-b22af46b01c2.png)

**Comment by rhazdon** [comment]
Hi @TheGroundZero,

yes, there is an option in hugo: `enableEmoji     = true` (see https://gohugo.io/getting-started/configuration/).

**Comment by TheGroundZero** [comment]
I suppose this will disable emoji's as a whole? Not specifically in code blocks?

I do like the emoji's in text, but for obvious reasons would prefer not to have them appear in code blocks.
