### ISSUE TITLE
lines within code blocks with linenos turned on don't line up

### ISSUE THREAD

**Issue by gokeefe** [rhazdon/hugo-theme-hello-friend-ng#106]
When line numbers are turned on in a code block, the rows don't line up.

The cell containing the line numbers inherits margin from the user agent stylesheet and padding from [assets/scss/_main.scss](https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/assets/scss/_main.scss#L159), while the cell containing the code appears to get both margin and padding from PrismJS. ([assets/scss/_prism.scss](https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/assets/scss/_prism.scss#L35-L36))

![screenshot](https://user-images.githubusercontent.com/126059/74574129-d8f9b980-4f3f-11ea-95eb-dbef655298f3.png)

**Comment by rhazdon** [comment]
How do you enable line numbers?

**Comment by gokeefe** [comment]
```yaml {linenos=table}
    version: "3.7"

    services:
    <clip>
    ```

**Comment by rhazdon** [comment]
AWESOME. I didn't even know that this feature exists. xD

**Comment by rhazdon** [comment]
Fixed. ;)
