### ISSUE TITLE
Error publishing website

### ISSUE THREAD

**Issue by TheGabrielHoward** [rhazdon/hugo-theme-hello-friend-ng#109]
I'm getting this error from the template:
There was a YAML syntax error on line 2 column 1 in <unknown>): did not find expected key while parsing a block mapping at line 2 column 1 YAML Exception reading themes/hello-friend-ng/archetypes/posts.md: (<unknown>: did not find expected key while parsing a block mapping.

**Comment by rhazdon** [comment]
Hi @TheGabrielHoward, this sounds weird... :D Can you please show me the yaml of your post?

**Comment by TheGabrielHoward** [comment]
> Hi @TheGabrielHoward, this sounds weird... :D Can you please show me the yaml part of your post?

what do you mean? by the way i am getting another weird error now: https://del.dog/ithunulere.txt

**Comment by TheGabrielHoward** [comment]
Building locally using "hugo server" doesn't send any error message, only github pages shows those errors

**Comment by rhazdon** [comment]
Honestly, I can't reproduce your issue. Have you tried creating and uploading yours? Or did you try to deploy the exampleSite?

**Comment by TheGabrielHoward** [comment]
> Honestly, I can't reproduce your issue. Have you tried creating and uploading yours? Or did you try to deploy the exampleSite?

Was my fault, i set up semaphoreCI to build the web and then publish to github, now it works, i was putting source into github and try to build
