### ISSUE TITLE
Error when building a new project on a ubuntu 16/04

### ISSUE THREAD

**Issue by markdimi** [rhazdon/hugo-theme-hello-friend-ng#11]
Hello.
I have the official hugo package in apt:
`hugo version`
`Hugo Static Site Generator v0.40.1 linux/amd64 BuildDate: 2018-04-25T17:16:11Z`
After creating a new hugo site following the official guide I run `hugo server -t hello-friend-ng` as stated in the themes tutorial and I get the following error:

`Building sites … ERROR 2019/04/03 13:38:47 Failed to add template "theme/partials/head.html" in path "/home/mark/Work/MARKOSBLOG/markos-weblog/themes/hello-friend-ng/layouts/partials/head.html": template: theme/partials/head.html:26: function "resources" not defined                                                                                                                    
ERROR 2019/04/03 13:38:47 Failed to add template "theme/partials/javascript.html" in path "/home/mark/Work/MARKOSBLOG/markos-weblog/themes/hello-friend-ng/layouts/partials/javascript.html": template: theme/partials/javascript.html:1: function "resources" not defined                                                                                                                    
ERROR 2019/04/03 13:38:47 theme/partials/head.html : template: theme/partials/head.html:26: function "resources" not defined                                                                   
ERROR 2019/04/03 13:38:47 theme/partials/javascript.html : template: theme/partials/javascript.html:1: function "resources" not defined                                                        
ERROR 2019/04/03 13:38:47 Error while rendering "taxonomyTerm" in "": template: /home/mark/Work/MARKOSBLOG/markos-weblog/themes/hello-friend-ng/layouts/_default/list.html:4:11: executing "/home/mark/Work/MARKOSBLOG/markos-weblog/themes/hello-friend-ng/layouts/_default/list.html" at <partial "head.html" ...>: error calling partial: template: "theme/partials/head.html" is an incomplete or empty template                                                                                                                                                                         
ERROR 2019/04/03 13:38:47 Error while rendering "home" in "": template: /home/mark/Work/MARKOSBLOG/markos-weblog/themes/hello-friend-ng/layouts/index.html:4:11: executing "/home/mark/Work/MARKOSBLOG/markos-weblog/themes/hello-friend-ng/layouts/index.html" at <partial "head.html" ...>: error calling partial: template: "theme/partials/head.html" is an incomplete or empty template  
ERROR 2019/04/03 13:38:47 Error while rendering "404" in "": template: /home/mark/Work/MARKOSBLOG/markos-weblog/themes/hello-friend-ng/layouts/404.html:4:11: executing "/home/mark/Work/MARKOSBLOG/markos-weblog/themes/hello-friend-ng/layouts/404.html" at <partial "head.html" ...>: error calling partial: template: "theme/partials/head.html" is an incomplete or empty template       
Total in 30 ms
Error: Error building site: logged 4 error(s)
`

I tested with the ananke theme but there were no errors, so I assume this would be related to hello-friend-ng.

**Comment by rhazdon** [comment]
Hi @markdimi, thank you for your message. 

As I see you have installed hugo version `v0.40.1`, which is quiet old. Could you try it with a newer version? The current one is [0.54.0](https://github.com/gohugoio/hugo/releases).

I will update the required version in the theme.toml.

**Comment by markdimi** [comment]
Great. I purged the old hugo and used the one in snap which is the latest/stable and the theme runs without any problems. Thanks
