### ISSUE TITLE
Adding custom functions to theme.js

### ISSUE THREAD

**Issue by hrvstr** [rhazdon/hugo-theme-hello-friend-ng#110]
Hi, I am trying to add more functionality to the theme-switcher in this theme. I want to control the colors of a background animation ([VantaJS](https://www.vantajs.com)).

https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/ced2f28558f3a15b1531b16b4aef224480f07e05/assets/js/theme.js#L1-L23

I already managed to add a function when the theme switches from the light to the dark theme but can't get it to work the other way. Can you point me in the right direction?

```js
// Toggle theme

const getTheme = window.localStorage && window.localStorage.getItem("theme");
const themeToggle = document.querySelector(".theme-toggle");
const isDark = getTheme === "dark";
var metaThemeColor = document.querySelector("meta[name=theme-color]");

if (getTheme !== null) {
  document.body.classList.toggle("dark-theme", isDark);
  isDark ? metaThemeColor.setAttribute("content", "#252627") : metaThemeColor.setAttribute("content", "#fafafa");
}

themeToggle.addEventListener("click", () => {
  document.body.classList.toggle("dark-theme");
  window.localStorage &&
    window.localStorage.setItem(
      "theme",
      document.body.classList.contains("dark-theme") ? "dark" : "light",
    );

    // Animation switch light
    effect.setOptions({baseColor: 0xFFFFFF});
  document.body.classList.contains("dark-theme") ?
    metaThemeColor.setAttribute("content", "#252627") : metaThemeColor.setAttribute("content", "#fafafa");

    // Animation switch dark
    effect.setOptions({baseColor: 0x000000});
  ;
});
```

**Comment by skymonio** [comment]
Hi! I'm trying to implement something just like this. 
Did you manage to make it work both ways?

**Comment by hrvstr** [comment]
> Hi! I'm trying to implement something just like this.
> Did you manage to make it work both ways?

Nope, never got this working. I created a related issue [here](https://github.com/tengbao/vanta/issues/54) but didn't really made any progress.

**Comment by rhazdon** [comment]
I think this is gone? So closed now. :)
