### ISSUE TITLE
cursor logo doesn't always flash when set to

### ISSUE THREAD

**Issue by famesjranko** [rhazdon/hugo-theme-hello-friend-ng#114]
I noticed that the cursor only appears to flash on certain browsers/devices. For instance, the cursor logo doesn't flash on chrome desktop or android for me - this includes both my site and your own.  However, on android and using the samsung browser the cursor does flash for both my site and your own. 

I've been looking through the layout files and can't figure out why it would behave like this. It's not a big deal, just a small annoyance. 

Is this expected behaviour?

**Comment by rhazdon** [comment]
Hi @famesjranko,

Well, I have tested on macOS Chrome, Safari, Firefox and on Windows Chrome, Firefox and Opera and can't reproduce your error. The cursor flashes everywhere as expected. Unfortunately I don't have Android, so I can't test it there. Have you checked if the browser has written anything to the console?

**Comment by famesjranko** [comment]
hi @rhazdon 

Thanks for trying to track this down with me. 

I did just find what the culprit was: It's windows  performance settings, of all things.  Such an annoying thing to discover after spending ages working through possible CSS causes via chrome dev panel. 

To reproduce: in 'Performance Options', unselect 'Animate controls and elements inside windows'.
