### ISSUE TITLE
Potential Security Vulnerability

### ISSUE THREAD

**Issue by mithi** [rhazdon/hugo-theme-hello-friend-ng#119]
Dependabot suggests to upgrade minimist to version 1.2.2 or later. 

Thanks! ❤️

**Comment by rhazdon** [comment]
Hi @mithi, thank you for the report. :)
Fixed with 8e253b2563ee348b33dc03d3db6bef9813357e3f

**Comment by mithi** [comment]
Thanks @rhazdon !
I'm using your theme it's my favorite out of the hundreds I've checked out.
https://mithi.github.io/robotics-blog/
Thanks again!
