### ISSUE TITLE
Dont render <h1> at index.html

### ISSUE THREAD

**Issue by ccantos** [rhazdon/hugo-theme-hello-friend-ng#12]
Building sites … WARN 2019/04/10 10:38:16 Page's .RSSLink is deprecated and will be removed in a future release. Use the Output Format's link, e.g. something like: 
    {{ with .OutputFormats.Get "RSS" }}{{ . RelPermalink }}{{ end }}.

**Comment by ccantos** [comment]
Instead of rendering index.html render list.html. It can be seen in the source code.
For that reason it does not render the title and the icons of the index I think.

When do `Hugo` folder public/index.html render list.html.
When do `Hugo server -t hello-friend-ng` correctly render.

**Comment by rhazdon** [comment]
Hi @ccantos,

thanks for reporting the issue with the RSS deprecation warning. I fixed it. :)

Regarding the `index.html`: Using the `index.html` as the entry point for the homepage is totally fine. The Hugo docs (https://gohugo.io/templates/homepage/) are a bit more descriptive. :) In short: Technically the `index.hml` _is_ a list view, but a special kind of. 

But why shouldn't the theme render the `<h1>` tag on the root webpage?

**Comment by ccantos** [comment]
My problem is the same as this one.  https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/14#issue-432651954
I close this issue and will be aware of that issue.
