### ISSUE TITLE
Change cursor colour with theme colour change?

### ISSUE THREAD

**Issue by famesjranko** [rhazdon/hugo-theme-hello-friend-ng#121]
Hey, 

I was wondering if it'd be possible to change the cursor colour when the theme colour changes? For example, a pink cursor for dark theme and a dark grey cursor for light theme. 

Also, thanks for creating/sharing this. I love the clean and concise design layout of your theme. Great work!

**Comment by famesjranko** [comment]
Or, is there a way to keep the header as the dark theme colour setting across both themes? 

I've looked at the css trying to see if I can do either of these myself without luck thus far.

**Comment by rhazdon** [comment]
Hi @famesjranko, 

currently there is no way to change the icon cursor color with a theme switch. :)
