### ISSUE TITLE
Posts next/previous links

### ISSUE THREAD

**Issue by ptlawrence** [rhazdon/hugo-theme-hello-friend-ng#122]
Hi,
I love your theme, thank you for building it!
I'm using v0.67.0 of hugo and I'm finding that the next and previous links are switched on the posts. That is, the first button, previous arrow, is actually linking to the more recent post, while the second button, with next arrow, is linking to the older post.
Am I doing something wrong, or has hugo switched the order of the list items in a section or something?  I've written a fix for layouts/posts/single.html in my local copy, but I'm not sure if this is a bug in your theme, or if it's user-error on my part.
Thanks for considering.  -- Peter

**Comment by rhazdon** [comment]
Hi @ptlawrence, 

Did you have checked the `date` of your posts? Because this is the date the next/previous links are looking for ordering the posts...

**Comment by ptlawrence** [comment]
Hi,

Thanks for your response.  Yes, I checked the date of my posts. Which version of hugo are you using? I'm using v0.67.0. Maybe that's the problem?

Thanks again,
Peter

**Comment by rhazdon** [comment]
v0.69.0. 

This theme just uses the hugo functions for this buttons... if there is something wrong with it, it might be related to hugo.

**Comment by rhazdon** [comment]
Hold on... I can reproduce it... Let me take a closer look. :)
