### ISSUE TITLE
Feature: sticky table of contents

### ISSUE THREAD

**Issue by willis7** [rhazdon/hugo-theme-hello-friend-ng#127]
Unfortunately, I do not have the skills to add this feature, but I wondered if you agree; this would be awesome for this theme.

https://ma.ttias.be/adding-a-sticky-table-of-contents-in-hugo-to-posts/
https://www.bram.us/2020/01/10/smooth-scrolling-sticky-scrollspy-navigation/

**Comment by rhazdon** [comment]
I think I wont add this anymore. But maybe in another (future) theme. :)
