### ISSUE TITLE
Options to customize home/index page

### ISSUE THREAD

**Issue by govinda-attal** [rhazdon/hugo-theme-hello-friend-ng#13]
Thanks the theme looks incredibly cool!

Could you please advise simple ways to customize home page with background images, some more content, etc?

Any doco could help, sorry for being a newbie with Hugo and starting with this theme.

**Comment by rhazdon** [comment]
Hi @govinda-attal,

thank you very much. :)

Regarding your question: The theme absolutely conforms to Hugo standards. Everything you need you will find in the [exampleSite dir](https://github.com/rhazdon/hugo-theme-hello-friend-ng/tree/master/exampleSite) as well as in the [official Hugo documentation](https://gohugo.io/getting-started/). A very interesting part is [about content management](https://gohugo.io/content-management/). For changing background images just use the [Front Matter](https://gohugo.io/content-management/front-matter/) tag `images like here: 

``` yaml
images:
  - https://picsum.photos/1024/768/?random
```

I hope this helps you. :)

**Comment by govinda-attal** [comment]
You are hero mate! 
I am using it for my blog site 😊
