### ISSUE TITLE
Unable to access posts (copied from exampleSite)

### ISSUE THREAD

**Issue by gerardsimons** [rhazdon/hugo-theme-hello-friend-ng#132]
Hi there, when I follow the instructions the posts do not work right off the bat and I am not completely sure on how to get it to run. I undestood that there need to be some posts in content, so I copy some stuff over from exampleSite, the  but then I get this error:

```
ERROR 2020/04/12 23:43:32 Rebuild failed:

ERROR 2020/04/12 23:43:32 Failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:4:11: executing "_default/single.html" at <partial "head.html" .>: error calling partial: execute of template failed: template: _internal/opengraph.html:41:17: executing "_internal/opengraph.html" at <index $siteSeries $name>: error calling index: index of untyped nil

```

**Comment by thegumza** [comment]
I have same issue and I try to clone from panr/hugo-theme-hello-friend instead it's work but If this repo fix this I will try again. Thank you

**Comment by Jealno** [comment]
Same problem here. Waiting ur fix @rhazdon

**Comment by rhazdon** [comment]
Thank you for the report. Working on it. :)

**Comment by Jealno** [comment]
@rhazdon Adding `series   = "series"` on taxonomies, fixed the problem

**Comment by rhazdon** [comment]
@Jealno, yeah, it seems like this is unfortunately the issue. 

In https://gohugo.io/templates/internal/#open-graph is documented, that the key "series" in `Taxonomies` must be set. In the case somebody don not want that, the template will check the existence of this key now. 

I have also updated the documentation in the README.

**Comment by adhisimon** [comment]
Looks like there is no need to check wheter "series" is set in taxonomies to include opengraph meta on current hugo version anymore.

I think we should remove that condition now, so opengraph meta properties can be generated on any page.
