### ISSUE TITLE
Can't justify text on /posts/

### ISSUE THREAD

**Issue by Jealno** [rhazdon/hugo-theme-hello-friend-ng#134]
Hi @rhazdon 
Im follow your tutorial to add` text-align:justify` on .content, set `justifyContent = true` on config.toml and rebuild scss with `hugo server -w --noHTTPCache --disableFastRender -v`. But that only affects the home page and doesn't affect /posts/. Can u fix it? Thankyou

**Comment by Jealno** [comment]
Btw, im fix the /posts/ justify problem. @rhazdon you need edit `exampleSites/config,toml` at section  `justifyContent` = false  # Set "text-align: justify" to .content.`. Change it to ` justifyContent = false  # Set "text-align: justify" to .post-content`

**Comment by rogeriobastos** [comment]
Hi @Jealno 
How did you fix this? I have the same problem.

**Comment by rhazdon** [comment]
Hi @Jealno, thanks for the comment. I have changed the docs. :)
