### ISSUE TITLE
Any way to remove "Powered by Hugo Made with ❤ by Djordje Atlialp" ?

### ISSUE THREAD

**Issue by jub0bs** [rhazdon/hugo-theme-hello-friend-ng#135]
Great theme! No offence, but I'd like to remove the mention

> Powered by Hugo Made with ❤ by Djordje Atlialp

Is there an option for that?

**Comment by rhazdon** [comment]
@jub0bs, this project is under mit license. Feel free to make any changes on your fork you want. :)
