### ISSUE TITLE
XMPP url not working

### ISSUE THREAD

**Issue by paapereira** [rhazdon/hugo-theme-hello-friend-ng#136]
I'm using with success the recently added xmpp social icon, but the url is translated as something like https://mypage/#RanD0m instead of the xmpp:user@myserver.com url.

```
  [[params.social]]
    name = "xmpp"
    url  = "xmpp:user@myserver.com"
```

This is probable due the the xmpp url format. Using this url in my about.md file as an example it works as expected.

**Comment by rhazdon** [comment]
Hi @paapereira, I think this is related to the default behaviour of the `<a />` tag. You must provide a protocol. If not, `<a href="something:like@this">My Link</a>` will always link to `{http|https}://{mypage.com}/something:like@this`.

**Comment by paapereira** [comment]
Ok. Thanks you.
