### ISSUE TITLE
Categories in posts

### ISSUE THREAD

**Issue by paapereira** [rhazdon/hugo-theme-hello-friend-ng#137]
In the end of a post I can see the tags, but not the categories. I believe this is due to this particular theme.
If I manually go to mysite.com/categories I can see the categories.

In my config.toml
```
[taxonomies]
  tag      = "tags"
  category = "categories"
```

In my posts
```
categories:
  - general
tags:
  - hugo
```

**Comment by rhazdon** [comment]
Hi @paapereira, yes the categories are not displayed. :) I'm not sure if I would like this see the categories next behind the tags. What do you think?

**Comment by paapereira** [comment]
Yeah, in the mean while I saw the url can be set with the category, something like https://mysite.com/posts/category/2020/05/mypost/
I'm still deciding :) but I'm not sure anymore.

Maybe bellow the title and before the text body ?

**Comment by rhazdon** [comment]
Added https://github.com/rhazdon/hugo-theme-hello-friend-ng/commit/e3402457805c0df65b96833f15579c4153c17700

:)
