### ISSUE TITLE
IsHome sometimes fails to recognise the home page, and the page title is not rendered

### ISSUE THREAD

**Issue by nicolas-navarro-guerrero** [rhazdon/hugo-theme-hello-friend-ng#14]
I am using the theme for the page indicated below. The front page is often rendered with the header and foot only. Somehow the variable .IsHome is not consistently updated.

In some opportunities, I realize I had removed an empty line in the config file and that triggers the error. However, sometimes I only add a new post without touching the config file, and the error is also triggered. I have not been able to pin point the source of the error.

https://cdstc.gitlab.io/task-force-on-action-and-perception/

**Comment by rhazdon** [comment]
Hi @nicolas-navarro-guerrero,

well, I discovered the same issue and I invested now some hours to find the problem. Do you maybe use `[taxonomies]` in your `config.toml`?

**Comment by ccantos** [comment]
With the same error. In my case:
```
[taxonomies]
  tag      = "tags"
  category = ""
```

**Comment by rhazdon** [comment]
Comment it out, if you do not use it. I don't know why, but this fixed it for me. Still investigating it, but I assume that this is a bug in Hugo.

**Comment by sam5558** [comment]
Hello @rhazdon @nicolas-navarro-guerrero ,
I had the same error. the fix works also for me (by commenting out the taxomonies section) it's probably be a bug :+1:

**Comment by siyagule** [comment]
Same issue, commenting out taxonomies worked for me. Thank you
