### ISSUE TITLE
Add animated cursors

### ISSUE THREAD

**Issue by SRITANU** [rhazdon/hugo-theme-hello-friend-ng#142]
Brilliant theme. Great work. I have two questions:

- At the centre of the page, I have my name and below that, I plan to include some 3-4 areas that I work on. Instead of writing them in a single line with backslashes, is it possible to have a "cursor typing and deleting the roles" kind of animation effect? Something like this: https://codepen.io/hi-im-si/pen/DHoup

- I'd like to make the footer a little bit smaller. Can you please tell me where's the option for that?
 ```
 © 2020  Sritanu Chakraborty  CC BY-NC 4.0
  Powered by Hugo  Made with ❤ by Djordje Atlialp
```

**Comment by SRITANU** [comment]
I could make the font size smaller with `style="font-size:12px"` in the `div` of the generated `index.html`.

**Comment by rhazdon** [comment]
Hi @SRITANU, 

thank you very much! :)

Regarding your first question: I do like the idea with this "cursor typing and deleting thing". But I'm not sure if this feature could be a little bit "too much" for the reader, because there is already this blinking cursor at the logo that is catching the eyes. But let me thing about this feature.  :)

How does it look like on your page?

**Comment by skymonio** [comment]
Great theme indeed! Many thanks! Jumping right into the conversation just to share a library for this purpose that I recently found as it might fuel your thoughts. Its called [Typeit](https://github.com/alexmacarthur/typeit) and you can see it in action in [Loveit Hugo theme](https://github.com/dillonzq/LoveIt). License aint really free though.

**Comment by SRITANU** [comment]
@rhazdon Here's my page, that I'm building. WIP.  http://mialgotech.ai/ 

@skymonio Thanks a bunch. :)

**Comment by rhazdon** [comment]
Heyho, well I think this feature is pretty cool, but it should not be really part of this theme, because an animating typo plus the blinking logo were too much blinky things in the end. I want it to stay simple and clean - without too much moving or blinking parts.
