### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by paapereira** [rhazdon/hugo-theme-hello-friend-ng#143]
Is there a way to add pagination in a posts section or limit the number of posts?

**Comment by rhazdon** [comment]
Hi @paapereira, yes, since 5 minutes. ;)

Just add `paginate  = 10` (or any other number you like) into your `config.toml`. 

The related commit: https://github.com/rhazdon/hugo-theme-hello-friend-ng/commit/23434e21029e1b0898770824b472b1caa3fc5dc7.
