### ISSUE TITLE
How to "build" the theme?

### ISSUE THREAD

**Issue by syvanpera** [rhazdon/hugo-theme-hello-friend-ng#148]
I forked my own copy of this repo and I would like to do some modifications to the styles, but I'm a bit lost at how to get those changes into effect. It seems that the resources/_gen - folder contains the compiled sass styles, but I'm not sure how I go about updating those files after I've done my changes to the source sass files.

**Comment by rhazdon** [comment]
Hi @syvanpera, 

honstly: Nothing. ;) Just run `hugo` to build your page or `hugo server`. This is because the theme uses [Hugo asset pipelines](https://gohugo.io/hugo-pipes/introduction/). https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/layouts/partials/head.html#L26

:)
