### ISSUE TITLE
Section list pages all display posts

### ISSUE THREAD

**Issue by Robleh** [rhazdon/hugo-theme-hello-friend-ng#152]
Looks like 23434e21029e1b0898770824b472b1caa3fc5dc7 may have broken section lists for sections other than /posts. No matter which section is browsed to, the files from /posts are listed.

I think the issue is [here](https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/23434e21029e1b0898770824b472b1caa3fc5dc7/layouts/_default/list.html#L3). $contentTypeName always references `posts` instead of a variable like `.Section`. Changing that seemed to fix the issue on my end, but I did not test if the new pagination features are still intact.

I sent pull request #151 with my simple fix in case it's all that's needed upstream.

**Comment by rhazdon** [comment]
Thanks!

**Comment by rhazdon** [comment]
I discovered also an issue with wrong pluralization. Fixed here: https://github.com/rhazdon/hugo-theme-hello-friend-ng/commit/9f3c15b70e61cf8eb466aa96a34250a27c3ac7b0.

**Comment by Robleh** [comment]
My pleasure, thanks for the awesome theme @rhazdon.
