### ISSUE TITLE
[Wish] Add icons

### ISSUE THREAD

**Issue by niklas-fischer** [rhazdon/hugo-theme-hello-friend-ng#153]
Hi!
your theme is absolutely amazing! I'd like to have a few more icons:
[Pixelfed](https://pixelfed.org/)
[Codeberg](https://codeberg.org/)
[Signal](https://signal.org/)

Wish you can make it possible :-)
Thank you.

**Comment by FoxMaccloud** [comment]
Mind adding "box"
from https://feathericons.com/?query=box
while you are at it? :)

**Comment by j-5chneider** [comment]
And  
[Researchgate](https://simpleicons.org/?q=researchgate)  
[Google Scholar](https://simpleicons.org/?q=scholar)  
Those are quite vital for scientists :)  
Thanks

**Comment by rhazdon** [comment]
All icons added - excepted Pixelfed and Codeberg, because there aren't officially provided icons yet.

**Comment by jalemann** [comment]
@rhazdon If you would like to add it, there is a Codeberg icon now available at: https://codeberg.org/Codeberg/Design/src/branch/main/logo/icon/svg/codeberg-logo_icon_blue.svg
