### ISSUE TITLE
Blank page with post

### ISSUE THREAD

**Issue by GriefNorth** [rhazdon/hugo-theme-hello-friend-ng#156]
After applying this commit 9f3c15b70e61cf8eb466aa96a34250a27c3ac7b0 page with posts is blank
and if I pushed to gitlab, pipelines stuck on deploying.

**Comment by rhazdon** [comment]
Hi @GriefNorth, thank you for your report. 
Do you have a „paginator“ config in your config.toml?

https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/README.md#how-to-configure

**Comment by GriefNorth** [comment]
At now i set paginate = 10, contentTypeName = "posts" and all links show oly page with posts.

**Comment by rhazdon** [comment]
Hi @GriefNorth,

please check out the last commit. I hope this should fix your issue. 
`contentTypeName` is not needed anymore.

**Comment by GriefNorth** [comment]
Thx, at now all works well
