### ISSUE TITLE
License and attribution.

### ISSUE THREAD

**Issue by mkanakis** [rhazdon/hugo-theme-hello-friend-ng#159]
Hi,

First of all, thanks for the great theme.

I would like to ask one question regarding the license. On the repository you have MIT which does not require attribution. 
However, the exampleSite and Demo you have set them up with CC which does require attribution. 

I am guessing MIT is the official one on the repository, but I would like to make sure that this is the case and you do not require attribution before removing the copyright notice.

Have a nice day!

Best,
Marios.

**Comment by Vorlif** [comment]
Hi,

I'm not the owner of the repositories but have seen that the issue #135 is similar.  Does that answer your question?

Best, 
Vorlif

**Comment by rhazdon** [comment]
Hi guys,

the content in the exampleSite directory is made by Hugo. Every theme on https://themes.gohugo.io/ has exactly the same exampleSite content. 

The theme itself is licensed under MIT. The content (blog posts) of my website are licensed under CC. But that does not affect this repo/theme. :)
