### ISSUE TITLE
Error running theme - TOCS: failed to transform scss/main.scss

### ISSUE THREAD

**Issue by a9e78rauijasdf** [rhazdon/hugo-theme-hello-friend-ng#161]
Hi,

Trying to run your theme with hugo v. 0.71.1-A301F6B2 on kubuntu 18.04.3. The following error appears:

Change of config file detected, rebuilding site.
2020-05-25 16:34:12.900 +0200
ERROR 2020/05/25 16:34:12 TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0" not found in file cache

The site displays:

TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0" not found in file cache

Hugo Static Site Generator v0.71.1-A301F6B2 linux/amd64 BuildDate: 2020-05-25T09:09:07Z
Reload Page 

It is installed as per the instructions on the Hugo Quickstart page. Any ideas...?

**Comment by a9e78rauijasdf** [comment]
Hugo Extended was needed - would be nice to have in the instructions :-) closing issue.

**Comment by huseyinsimsekk** [comment]
How did you solve this issue? Did it occur from Hugo?
