### ISSUE TITLE
Change color of blinking curso?

### ISSUE THREAD

**Issue by marcelo321** [rhazdon/hugo-theme-hello-friend-ng#170]
Sorry for the dumb question, is it possible to change the color of the blinking curso? if yes, how and where exactly do i need to edit it?

**Comment by pazyp** [comment]
Saw your issue, if you look in config.toml there is a nice example starting on line 87 to 93.

```
  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"

```

So youi want to remove the # from logoCursorColor variable and change the colour hex value (#67a2c9) to one that you like.
