### ISSUE TITLE
Feature request: Add params to adjust portrait image size

### ISSUE THREAD

**Issue by kogisin** [rhazdon/hugo-theme-hello-friend-ng#173]
I think it will be nice to have some params in [config.toml](https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/exampleSite/config.toml#L97) that will enable users to adjust portrait image size.

**Comment by justanotherlad** [comment]
Really need this feature

**Comment by justanotherlad** [comment]
I was wondering, is there a way to do the same from any of the html or css files atleast in the /themes folder, if not from the config.toml file, as of now?

**Comment by kogisin** [comment]
Hey @justanotherlad,
You can workaround this before having this feature approved.

1. Fork this repository 
2. Change `max-width` in `main.scss` file to whatever the image size you want your portrait to be. 

[You can reference mine](https://github.com/kogisin/hugo-theme-hello-friend-ng/blob/master/assets/scss/_main.scss#L105)

**Comment by rhazdon** [comment]
Here you go. 

``` toml
  [params.portrait]
    path     = "/img/image.jpg"
    alt      = "Portrait"
    maxWidth = "50px"
```

;)
