### ISSUE TITLE
comments: true is not used to show Disqus panel

### ISSUE THREAD

**Issue by prashantbhardwaj** [rhazdon/hugo-theme-hello-friend-ng#175]
Earlier only those pages had disqus embedded which had comments: true, however when I upgraded my theme to latest commit and built my website, now disqus is embedded in all the pages even on those where I don't have comments: true.

Is this because of any bug or is there any change in the way we embed disqus?

Please suggest.

**Comment by rhazdon** [comment]
Hi @prashantbhardwaj, 

the issue should be fixed now with a706f10387c20b90effa11a5f3dc8eb330703378. Can you verify it?

**Comment by prashantbhardwaj** [comment]
Unfortunately, issue still exists.

**Comment by rhazdon** [comment]
Hi @prashantbhardwaj,

I checked it out again ad I can definitively confirm that it works. Please try it again with the current version. :)
