### ISSUE TITLE
A page to show tags in a cloud and a link on the top of home page to go to that tag cloud page

### ISSUE THREAD

**Issue by prashantbhardwaj** [rhazdon/hugo-theme-hello-friend-ng#179]
Hi,

Can we have a new feature in this theme to create a page which will have all the tags in the form of word cloud. There should be a way to put a link of this page on the header. Size of a tag on that page will be determined by the number of web pages linked to that tag. Clicking on any of the tag should redirect users to a page which has list of all the pages containing that tag.

thanks
Prashant

**Comment by rhazdon** [comment]
Hi @prashantbhardwaj, 

thanks for the question. No, I am not into word clouds and I wouldn't create one. But feel free to contribute something to this project. :)
