### ISSUE TITLE
How to select PrismJS theme

### ISSUE THREAD

**Issue by droctothorpe** [rhazdon/hugo-theme-hello-friend-ng#185]
How do I select a PrismJS theme?

The sample `config.toml` includes:

```
PygmentsCodeFences = true
PygmentsStyle = "monokai"
```

However, Pygment appears to have far less choices than PrismJS. 

Any input would be greatly appreciated. 

Thank you!

**Comment by droctothorpe** [comment]
Also, is there a way to set the home page to the posts page?

**Comment by rhazdon** [comment]
Hi @droctothorpe, 

there is currently no configurable way to change the theme. You would have to inject your own prismjs javascript.   

To your second question: Im not sure at all, but maybe you could achieve this by replacing the content of `layouts/index.html` with the content of `layouts/_default/list.html`.

**Comment by droctothorpe** [comment]
Thanks @rhazdon!
