### ISSUE TITLE
Error building site: TOCSS: failed to transform "scss/main.scss"

### ISSUE THREAD

**Issue by TheGroundZero** [rhazdon/hugo-theme-hello-friend-ng#186]
Hi,

I downloaded a fresh copy of this repo as a git submodule.

Changing my config.toml to switch to this template and starting the Hugo localhost server, I get the following error:

```bash
$ hugo server
Built in 468 ms
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0" not found in file cache
```

**Comment by rhazdon** [comment]
Never saw this error before. Do you have the extended version of hugo installed? 

```
$ hugo version
Hugo Static Site Generator v0.73.0/extended darwin/amd64 BuildDate: unknown
```

**Comment by TheGroundZero** [comment]
> Never saw this error before. Do you have the extended version of hugo installed?
> 
> ```
> $ hugo version
> Hugo Static Site Generator v0.73.0/extended darwin/amd64 BuildDate: unknown
> ```

I don't, is that required?

```
$ hugo version
Hugo Static Site Generator v0.74.3 linux/amd64 BuildDate: 2020-07-23T20:37:11Z
```

**Comment by MayMeow** [comment]
I have 2 sites using this theme and both have same setting (copied config toml and theme) 1st one is building and 2nd ending with this error
