### ISSUE TITLE
Icon support for TryHackMe & HackTheBox

### ISSUE THREAD

**Issue by 0xb2b** [rhazdon/hugo-theme-hello-friend-ng#192]
Would you consider adding icon support for [TryHackMe](https://tryhackme.com) & [HackTheBox](https://hackthebox.eu) in the future?

Thanks!

**Comment by TheGroundZero** [comment]
You can add your badge using the image code, like this:

```md
{{< image src="https://www.hackthebox.eu/badge/image/161927" alt="Hack The Box" style="max-width: 256px; display: inline" >}}
```

**Comment by rhazdon** [comment]
Hi, for those icons there is no official icon to use on third party sites (e.g. from simpleicons). Because of that I rather do not want to add them into this theme.

**Comment by Sriraj151** [comment]
Please help the icon of Tryhackme

**Comment by Sriraj151** [comment]
https://assets.tryhackme.com/img/logo/tryhackme_logo_full.svg
