### ISSUE TITLE
Custom local/Google font?

### ISSUE THREAD

**Issue by haban3ra** [rhazdon/hugo-theme-hello-friend-ng#198]
Can I use custom fonts for the theme itself? I have tried editing sass files and imported local fonts on the `fonts` folder but to no luck. Help on what should I do? Thanks.

**Comment by rhazdon** [comment]
Hi @haban3ra,

yes, of course you can. 

The best way is to add (or change) the fonts in the font folder: https://github.com/rhazdon/hugo-theme-hello-friend-ng/tree/master/static/fonts. Just paste them in. Then add the fonts into the [SCSS font file](https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/assets/scss/_fonts.scss) and change the name of the used font https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/assets/scss/_main.scss#L17. 

Then it should work. :)

**Comment by matiasandina** [comment]
On my local machine, font rendering is working on chrome but not firefox, any ideas?
