### ISSUE TITLE
Theme toggle not working

### ISSUE THREAD

**Issue by solomonrajan** [rhazdon/hugo-theme-hello-friend-ng#199]
I've followed Hugo guide, I cant make theme toggle work when i host to my custom domain, but toggle works when im in <username>.github.io. @rhazdon

**Comment by rhazdon** [comment]
Hi @solomonrajan,

could you please tell me, where your page is hosted and how does your config.toml looks like?

**Comment by solomonrajan** [comment]
> Hi @solomonrajan,
> 
> could you please tell me, where your page is hosted and how does your config.toml looks like? 

I hosted in GitHub,

**Comment by rhazdon** [comment]
Hi @solomonrajan, 

okay. Well, I am sorry, but I can not help you without further information. "it doesn't work" is not enough unfortunately. 

I hope you can fix it on your own. Also, check the already closed issues they are related to github hosting.
