### ISSUE TITLE
Way to justify posts

### ISSUE THREAD

**Issue by ccantos** [rhazdon/hugo-theme-hello-friend-ng#20]
I was wondering how to justify the text of the posts. Shouldn't it be justified by default? In my opinion, it should already be justified, it looks better. Any help?

Every time I play something in the styles I destroy the page.

**Comment by DuncanmaMSFT** [comment]
Do you mean that instead of this:

![image](https://user-images.githubusercontent.com/18338424/56998129-03b88400-6b5f-11e9-9c7e-dd1ab1858682.png)

You want the post to look like this?

![image](https://user-images.githubusercontent.com/18338424/56998153-2185e900-6b5f-11e9-9050-fd8a19f872a3.png)

**Comment by DuncanmaMSFT** [comment]
If so, then you need to add this CSS to your site:

```css
.post-content p {
    text-align: justify;
}
```

Do you have a custom CSS file already? If not, add a 'style.css' to your static folder and then set the value of customCSS (in your config.toml file) to point at your new file, like this

```toml
 customCSS = ["/style.css"]
```

**Comment by ccantos** [comment]
It's working!
Thank you so much!

**Comment by ajdintrejic** [comment]
> If so, then you need to add this CSS to your site:
> 
> ```css
> .post-content p {
>     text-align: justify;
> }
> ```
> 
> Do you have a custom CSS file already? If not, add a 'style.css' to your static folder and then set the value of customCSS (in your config.toml file) to point at your new file, like this
> 
> ```toml
>  customCSS = ["/style.css"]
> ```

I'm trying to add padding to text I have a dummy css file just to see if its loading:
This is in my config.toml:
```
customCSS = ["/text_padding.css"]
```

```
> $ ls -la static
> total 28
> drwxr-xr-x  6 ajdin users 4096 May  2 10:21 .
> drwxr-xr-x 11 ajdin users 4096 May  2 10:21 ..
> drwxr-xr-x  2 ajdin users 4096 May  2 10:17 css
> drwxr-xr-x  2 ajdin users 4096 May  1 14:00 htb-mango
> drwxr-xr-x  2 ajdin users 4096 May  2 09:28 htb-openadmin
> drwxr-xr-x  2 ajdin users 4096 May  1 22:01 htb-postman
> -rw-r--r--  1 ajdin users  126 May  2 10:21 text_padding.css
```
```
.post-content > p {
    padding-top: 30px; !important
    background: red; !important
    border: 2px solid red; !important
}
```
But it's not loading when I visit a post, example <site>/posts/2020/05/hackthebox-postman-write-up/ the css file is not loaded. Am I missing something here?
