### ISSUE TITLE
social media icons not showing

### ISSUE THREAD

**Issue by angrypapa** [rhazdon/hugo-theme-hello-friend-ng#202]
It seems I can't display social media icons in the main page.

I Have `enableSharingButtons = true` in my `config.toml` but that seems to only affect blog pages. How can I display the social media icons below the `homeSubtitle` in the main page?

I tried to add the following as well but it's not working.

```
[[params.social]]
    name = "Twitter"
    icon = "fas fa-twitter"
    weight = 3
    url = "https://twitter.com/johndoe/"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/johndoe/"
```

Thank you.

**Comment by angrypapa** [comment]
figured it out.

**Comment by rosalogia** [comment]
Would you mind sharing what the problem was and how you solved it?

**Comment by unki2aut** [comment]
@rosalogia had the same problem. For me the solution looked like this:
```toml
[[params.social]]
    name = "twitter"
    url = "https://twitter.com/johndoe/"
```

The `name` had to be lower case. If you have a look at the code, the [`svg.html` partial](https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/layouts/partials/svg.html) looks for certain names to render them correctly.
