### ISSUE TITLE
Footer Has Extra Bullet if RSS is Disabled

### ISSUE THREAD

**Issue by 8F3E** [rhazdon/hugo-theme-hello-friend-ng#215]
The default footer leaves behind a bullet symbol (like this • one) when not rendering the RSS icon if it is disabled (through `disableKinds`).

**Comment by 8F3E** [comment]
Checking the source, I believe this is because a `<span>` is not inside the conditional statement.

Happy to make a PR and fix.

**Comment by rhazdon** [comment]
Thank you! :)
