### ISSUE TITLE
Sharing buttons aligned vertically, waste space

### ISSUE THREAD

**Issue by TheHackerDev** [rhazdon/hugo-theme-hello-friend-ng#217]
Hello,

The share buttons are aligned vertically, each taking their own line:

![image](https://user-images.githubusercontent.com/2362857/93725251-922a0d00-fb7b-11ea-9b41-537ebda57852.png)

Is there a way to make it so they are either not block-aligned, or are displayed horizontally instead?

Thanks!

**Comment by rhazdon** [comment]
Was fixed a while ago... :)
