### ISSUE TITLE
better contrast?

### ISSUE THREAD

**Issue by YusufHegazy** [rhazdon/hugo-theme-hello-friend-ng#219]
I find the grey background with the slightly darker grey font is not the best for the eye
any plans to fix that contrast, or point me to the right direction to edit it to my liking

**Comment by rhazdon** [comment]
Hi @YusufHegazy,

this is the point where you can change it. :)

https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/assets/scss/_variables.scss#L11
