### ISSUE TITLE
menu order

### ISSUE THREAD

**Issue by hmmatos** [rhazdon/hugo-theme-hello-friend-ng#221]
is there a way to change the order of the menu? 
now it is in alphabetical orde, right? 

```
[menu]
  [[menu.main]]
    identifier = "c"
    name       = "c"
    url        = "c/"
  [[menu.main]]
    identifier = "b"
    name       = "b"
    url        = "b/"
 [[menu.main]]
    identifier = "a"
    name       = "a"
    url        = "a/"
```

![2020-10-01 14_06_04-HUGO MATOS — Network Architect](https://user-images.githubusercontent.com/4135196/94813005-64e92480-03ef-11eb-85a5-15e7bf2f39eb.png)

How can I put the 'c' first?

**Comment by Reijnn** [comment]
Add a weight attribute like so:

`[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
    weight     = "1"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
    weight     = "2"
  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "projects/"
    weight     = "3"`

**Comment by hmmatos** [comment]
@Reijnn thanks
