### ISSUE TITLE
baseURL without domain name

### ISSUE THREAD

**Issue by martinord** [rhazdon/hugo-theme-hello-friend-ng#225]
Hi there,

How could I configure this theme to be able to deploy it under two different domain names? So far, my `config.toml` looks something like this:
```
baseURL = "https://mydomain.tld"
```
I would like to have some configuration so that I can publish the generated html files, for example, under all these base URLs:
- https://mydomain.tld
- https://another.tld/blog
- https://ipfs.io/ipns/mydomain.tld/

For this, I tried using `"/"` as baseURL, but it does not generate valid links.

Thanks a lot

**Comment by rhazdon** [comment]
Hi @martinord,

the `baseURL` setting comes from hugo itself (https://gohugo.io/getting-started/configuration/#all-configuration-settings). 

As I see it's not possible to save values like an array. But you could write maybe a custom deployment script for your case ...

**Comment by martinord** [comment]
Sorry for the late response @rhazdon. 

I found a workaround for my problem. I hope that helps someone:

If you configure `baseURL = ""` and enable `relativeURLs = true`, then your site will work on any deployment.
