### ISSUE TITLE
Dark mode/light mode not working

### ISSUE THREAD

**Issue by orangemn6** [rhazdon/hugo-theme-hello-friend-ng#233]
I set my site to go on https://jacobgoldstein.tk , but the light/dark mode toggle isnt working. Can someone please help!!?

**Comment by rhazdon** [comment]
Hi @orangemn6, 

it seems you have some issues with your assets. :) 

```
Cannot load script https://jacobgoldstein.tk/bundle.min.5c2f64632321fe361557377f6c5eb763531be2d7d69d897575d624ede040820dc17decf1350779061fd11db3ad89467cbddb12a07d171581667761c6f5ce547b.js. Failed integrity metadata check. Content length: 323063, Expected content length: -1, Expected metadata: sha512-XC9kYyMh/jYVVzd/bF63Y1Mb4tfWnYl1ddYk7eBAgg3BfezxNQd5Bh/RHbOtiUZ8vdsSoH0XFYFmd2HG9c5Uew==
```

**Comment by rhazdon** [comment]
Please check your server config and your release. I would recommend to redeploy your project.

**Comment by orangemn6** [comment]
I re-installed the theme and redployed. It still does not work

**Comment by orangemn6** [comment]
also I am using Netlify

**Comment by Sov3rain** [comment]
Reporting same thing here, using Netlify, switching light/dark theme is not working.

**Comment by Sov3rain** [comment]
Hey, reporting the same thing here. I'm hosting my website on Netlify too. I don't think it's related though. When opening the browser console, here it's what i'm getting:

![image](https://user-images.githubusercontent.com/10755450/99193160-75731580-2777-11eb-96b0-d1c5645462cf.png)

I don't get the custom fonts too. I don't know if it's related to this theme in particular, or just a problem with the overall configuration.

I must say that I've got my own domain name, and when accessing the website via the Netlify domain (*.netlify.app) everything works. Things are broken when I try to access my website through my own domain name.

**Comment by orangemn6** [comment]
yes. that is what I am getting @Sov3rain

**Comment by orangemn6** [comment]
I just went on your site and it worked for me @Sov3rain

**Comment by Sov3rain** [comment]
> I just went on your site and it worked for me @Sov3rain

From which URL? The one on the Netlify domain works fine indeed, but if you try to access it through my own domain, it doesn't.

https://samuelduval.netlify.app -> works
https://samuelduval.fr -> doesn't work

Seems related to https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/16 and https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/30

**Comment by orangemn6** [comment]
@Sov3rain both of them work

**Comment by Sov3rain** [comment]
> @Sov3rain both of them work

Yes, now it works because I solved the problem. It used the wrong url in the parameter "baseURL". You need to put your own domain name, not the one from Netlify. Now that I think of it, it makes sense. I can only blame my lack of knowledge in Web development.

I tried the solution at #30 with no luck, and I don't know if should work for my case or not.

**Comment by orangemn6** [comment]
My baseurl is my domain name

**Comment by Sov3rain** [comment]
Did you try to add crossorigin back into the javascript.html partial?

**Comment by orangemn6** [comment]
@Sov3rain when I do that netlify build fails

**Comment by orangemn6** [comment]
@Sov3rain net;ify built and it doesnt work

**Comment by Sov3rain** [comment]
Sorry to hear that. I'm running out of ideas here, and my skill in web development are very limited. At least I can point you to this thread: https://community.netlify.com/t/javascript-does-not-load-after-adding-custom-domain/26041/7.

People at Netlify are answering questions pretty fast, and I think your problem is not strictly related to this theme.

Good luck.

**Comment by orangemn6** [comment]
It works!! I just had the baseurl without www

**Comment by d3vilbug** [comment]
I was facing the same issue but after putting www along with domain in baseurl, it is working perfectly fine.
