### ISSUE TITLE
All posts have jan 1 as date

### ISSUE THREAD

**Issue by orangemn6** [rhazdon/hugo-theme-hello-friend-ng#234]
exactly what the title says. my site is jacobgoldstein.tk

**Comment by prcutler** [comment]
Do you have a date field in the front matter of each post?

Looks similar to this (from one of my blog posts at https://github.com/prcutler/paulcutler.org/commit/b9d55363dd7003263f79228e42de14bf85b7bf35#diff-f18323d5e83cc7e3abcd8d06f9cdfa8a5dc959f4d1cc919c3430ecc732b74a3e)

---
title: Practice Cuts
author: Paul Cutler
type: post
date: 2020-04-11T19:00:00
categories:
  - Arcade
tags:
  - Arcade
  - Woodworking
---

**Comment by orangemn6** [comment]
here is my data field:
---
title:
date:
draft:
---

**Comment by orangemn6** [comment]
i tried your data field and it worked thanks
