### ISSUE TITLE
Images not displaying. 

### ISSUE THREAD

**Issue by rajganeshp** [rhazdon/hugo-theme-hello-friend-ng#235]
I have a website https://www.connectthoughts.com. it's working fine. But if you got "Posts", and "RedTeam" blog for example, it's not displaying the image. the image is located in the Redteam folder. Can you give me some troubleshooting tips? thanks.

**Comment by rhazdon** [comment]
Hi @rajganeshp, 

you can try this example here: https://github.com/rhazdon/hugo-theme-hello-friend-ng#image. 

Also make sure that your images are in the static folder. :)
