### ISSUE TITLE
 TOCSS: failed to transform "scss/main.scss" (

### ISSUE THREAD

**Issue by michaelsync** [rhazdon/hugo-theme-hello-friend-ng#236]
I am getting this error when I build a Hugo with this theme. 

```
Start building sites …
Built in 23 ms
Error: Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss): resource "scss/scss/main.scss_de1a7f5f1c8c46959803c429bb697ff0" not found in file cache
```

* Hugo version: Hugo Static Site Generator v0.76.5-60F0725B windows/amd64 BuildDate: 2020-10-14T15:16:53Z
* The site is a new site. I just create it using hugo new site. 
* Windows 10
* Cmder + Powershell

**Comment by softcat** [comment]
I am experiencing the same problem after upgrading the theme to the newest git version. Using Hugo 0.76.5

**Comment by prcutler** [comment]
You need to install the extended version of Hugo. This is required for the build in CSS processors.

See:  https://gohugo.io/getting-started/installing/#source

You can also search the closed issues for more help if needed.

**Comment by mstahl** [comment]
I'm getting this same thing but unrelated to using the extended version. I see that if you're not using the extended version, it gives a different error message. My error message is identical to michaelsync's:

```
Error: Error building site: TOCSS: failed to transform "sass/styles.scss" (text/x-scss): resource "scss/sass/styles.scss_c25f88f67e8e33f20619c76cbf49f33c" not found in file cache
```

I'm trying to get this working on AWS Amplify. In the build settings I've changed my Hugo version to `latest+extended` but that doesn't seem to fix it. When I change it to `latest`, I get the error message that says `this feature is not available in your current Hugo version`. I get the file cache error message if I use the version I'm using locally, `0.111.3+extended`.

So, something's probably missing from my AWS Amplify configuration but I can't tell what it is. I don't wanna have to do a custom Docker image to build this bad boi.
