### ISSUE TITLE
The publication time of the posts is maintained in one minute

### ISSUE THREAD

**Issue by iambouali** [rhazdon/hugo-theme-hello-friend-ng#238]
Hello,

The publication time of the posts is maintained in 1 minute, it is not updated.

![hello_world](https://user-images.githubusercontent.com/74378500/99136215-0df88100-2624-11eb-95a1-c56802b55a09.png)

How can I fix this issue ? 

Regards

**Comment by rhazdon** [comment]
One minute is the minimum. :)  Just write content! =)
