### ISSUE TITLE
标题不显示

### ISSUE THREAD

**Issue by ZeKunLi** [rhazdon/hugo-theme-hello-friend-ng#24]
There is no problem with not displaying the title local view in the middle of my github deployed blog

**Comment by rhazdon** [comment]
Hi @ZeKunLi,

sorry, but I do not understand the issue right know. What kind of problem do you have?

**Comment by ZeKunLi** [comment]
hello @rhazdon ,
This is my blog address https://zekunli.github.io/
The introduction does not show.
Local is ok.

**Comment by ZeKunLi** [comment]
resolved
