### ISSUE TITLE
How to find out if user selected dark or light theme?

### ISSUE THREAD

**Issue by kuleje** [rhazdon/hugo-theme-hello-friend-ng#244]
Hey, I'd like to show a different version of an image depending on which version of the theme is selected, but I'm a bit lost how to do it.

**Comment by SerhatTeker** [comment]
You can find `theme` `const` in  `assets/js/theme.js`:

https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/44e11417bb18943d6612042b0f92055c47c07dfa/assets/js/theme.js#L3

**Comment by rhazdon** [comment]
Thank you @SerhatTeker for answering! :)
