### ISSUE TITLE
Suggested change to logo.html

### ISSUE THREAD

**Issue by bftsystems** [rhazdon/hugo-theme-hello-friend-ng#247]
Hey, as this is a simple suggestion, I figured it was easier to submit as an issue rather than through a pull. I suggest updating `row 6` in `layouts/partials/logo.html` as follows. This allows the use of a variable for the logo__mark, rather than being hardcoded in html.

`<span class="logo__mark">{{ with .Site.Params.Logo.logoMark }}{{ . }}{{ else }}>{{ end }}</span>`

This goes together with the following variable in `config.toml` (for example).

```
[languages.en.params.logo]
  logoMark = "[-]"
```

In any case, thanks for all your work on this theme.

**Comment by rhazdon** [comment]
Hi @bftsystems, thank you for the suggestion. I've added your idea just right now. https://github.com/rhazdon/hugo-theme-hello-friend-ng/commit/a46b6f603209175f0a9afa0765a1a6c7c041e8ff
