### ISSUE TITLE
Anyway to force the dark theme?

### ISSUE THREAD

**Issue by xealgo** [rhazdon/hugo-theme-hello-friend-ng#253]
I've gone through the readme and every config option as well as the JS files and layouts, but it doesn't appear there's a way to not have automatic dark/light mode.

**Comment by Fahl-Design** [comment]
Hi @xealgo 
Same issue for me... 

it was removed with https://github.com/rhazdon/hugo-theme-hello-friend-ng/commit/79d0488087e845de80d35b099b968737d83fc8c7

**Comment by xealgo** [comment]
Seems like a bit of an oversight. I'm running Ubuntu which really doesn't have dark and light theme, so I always get light.

**Comment by xealgo** [comment]
I just overwrote all of the scss styles to be dark ¯\_(ツ)_/¯

**Comment by Fahl-Design** [comment]
> Seems like a bit of an oversight. I'm running Ubuntu which really doesn't have dark and light theme, so I always get light.

I'm on Manjaro (KDE) with a dark theme that is detected by most apps, but this dosen't work either

> I just overwrote all of the scss styles to be dark ¯_(ツ)_/¯

hehe, I forked it and reverted the commit ;)

**Comment by TheHackerDev** [comment]
I'm also in agreement here. Can we please add the manual toggle back, at least?

**Comment by SerhatTeker** [comment]
> > Seems like a bit of an oversight. I'm running Ubuntu which really doesn't have dark and light theme, so I always get light.
> 
> I'm on Manjaro (KDE) with a dark theme that is detected by most apps, but this dosen't work either
> 
> > I just overwrote all of the scss styles to be dark ¯_(ツ)_/¯
> 
> hehe, I forked it and reverted the commit ;)

Did the similar thing: merged  `upstream/master` with `cherry-pick`s to exclude the commit https://github.com/rhazdon/hugo-theme-hello-friend-ng/commit/79d0488087e845de80d35b099b968737d83fc8c7.

**Comment by U5B** [comment]
Color Variables are located in /assets/scss/_variables.scss

**Comment by boastful-inaba** [comment]
Honestly, considering there are only 7 colors in the theme, it would be nice to have override options in the config.toml itself.  Of course using these would disable the autoswitch for dark/light, but if you're doing a custom color theme I assume you'd know what you're doing in that regard.

**Comment by TheGroundZero** [comment]
My windows 10 is setup to prefer Dark Mode, yet the site is now displayed in light mode.
I'd also like to have the option (again) to switch back to dark mode or to force it.

**Comment by fikriazh** [comment]
btw i have some trick to use dark color
here is [my site](https://mahasemesta.xyz)

i use stackbit then choose custom theme, paste repo, continue setup till ready, (i use forestry cms + netlify)
for me default is dark color

but when i clone to local and execute `hugo serve`, on local it will auto use light theme
push to github, auto deploy netlify, on internet it use dark color

the case is same when i "begin" this theme from local, when deploy to netlify, it will use light theme

summary : begin with stackbit then clone / edit to local
idk why it happen

**Comment by Cockhash** [comment]
It would be really nice if you undo the change!
I think most people would prefer to be able to set the default theme in config.toml and also to have the option to change it dynamically through a light/dark switch - as it was before.

**Comment by fikriazh** [comment]
> It would be really nice if you undo the change!
> I think most people would prefer to be able to set the default theme in config.toml and also to have the option to change it dynamically through a light/dark switch - as it was before.

btw i revert to commit version where i can use toggle to switch mode, here [my site](https://mahasemesta.xyz)

**Comment by amittos** [comment]
@fikriazh Nice work on bringing back the toggle. I'm not very well-versed with HTML/CSS/JS etc. I'm taking a look at your files [here](https://github.com/fikriazh/darknes) but I cannot figure out what to change to bring it back for my site. Can you please pinpoint me to the exact change? Thanks!

**Comment by matiasandina** [comment]
So if anyone is interested in forcing dark mode.

`_main.scss`
`_header.scss`
`_menus.scss`

Here's an example from `_header.scss`, you can revert the default behavior like this. 

`
.menu {
  background: $dark-background-header;
  z-index: 9999;

  @media (prefers-color-scheme: light) {
    background: $light-background-header;
  }
`

I still want my switch back and forth button back, if anybody finds a way to get it back into the menu with a toggle, please share

**Comment by Cockhash** [comment]
So, yeah, I don't think the author will revert the change and I also believe, that it's his good right to do with the project what he wants to do.

For those of you who want it the way it was before:
1.) Download the latest release, unzip it and cd into it
2.) With commit 79d0488 this change happened.
So now go carefully through https://github.com/rhazdon/hugo-theme-hello-friend-ng/commit/79d0488087e845de80d35b099b968737d83fc8c7 and undo every change - file by file - in your local hello-friend-ng theme.
After that you have the newest release but with the light/dark theme from earlier and you should be good to go.

**Comment by fikriazh** [comment]
> @fikriazh Nice work on bringing back the toggle. I'm not very well-versed with HTML/CSS/JS etc. I'm taking a look at your files [here](https://github.com/fikriazh/darknes) but I cannot figure out what to change to bring it back for my site. Can you please pinpoint me to the exact change? Thanks!

here i make [repo](https://github.com/fikriazh/Hugo-Hello-Friend-NG-Before-commit-auto-theme-) to the one step before the commit of auto theme, you can start from there, i better to use toggle...

**Comment by fikriazh** [comment]
> So if anyone is interested in forcing dark mode.
> 
> `_main.scss`
> `_header.scss`
> `_menus.scss`
> 
> Here's an example from `_menus.scss`, you can revert the default behavior like this. 
> 
> ```
> .menu {
>   background: $dark-background-header;
>   z-index: 9999;
> 
>   @media (prefers-color-scheme: light) {
>     background: $light-background-header;
>   }
> ```
> 
> On `_main.scss` besides shifting the color of text in body, the *strong* class needs to be changed like so:
> 
> ```
> em, i, strong {
>   color: white;
> 
>   @media (prefers-color-scheme: light) {
>     color: black;
>   }
> }
> 
> ```  
> 
> I still want my switch back and forth button back, if anybody finds a way to get it back into the menu with a toggle, please share

use [my repo](https://github.com/fikriazh/Hugo-Hello-Friend-NG-Before-commit-auto-theme-),

**Comment by matiasandina** [comment]
Thank you but I have already done changes to the repo and using yours as is would mean making them again. could you point to where you modified things? Otherwise it would be the same as doing #79d0488 by hand, right?

**Comment by undergroundwires** [comment]
I'd love to see 79d0488087e845de80d35b099b968737d83fc8c7 reverted too. The dark theme and the switch was great. Unfortunately up-to-date with `master` anymore. Hopefully community voice will be heard 🙏🏽

Maybe we could have `defaultTheme=auto` that sets the behavior to 79d0488087e845de80d35b099b968737d83fc8c7 and use the switch/manual way with `defaultTheme=dark/light`

**Comment by sasidakh** [comment]
I just spend an evening figuring this out. I was surprised the switch was removed I would like to have it configured. It was firstly not working. So i always got the light theme. Even if you get it to work, I think it should be configurable.

**Comment by maop** [comment]
i spent half an hour trying to figure how to CHOOSE the dark mode... and it lead me here.

Why isn't this a CHOICE?

**Comment by fikriazh** [comment]
> i spent half an hour trying to figure how to CHOOSE the dark mode... and it lead me here.
> 
> Why isn't this a CHOICE?

i use previous version when theme toggle is still available, then on the body tag i force from 'depend on theme toggle' to always 'dark mode', this my site [mahasemesta](https://mahasemesta.xyz)

**Comment by mondragonfx** [comment]
For those who are still interested, I came across this which includes the light/dark switch from previous commits by Mokytis => https://gitlab.com/mokytis/hello-friend-ng
I find git cloning this easier than adjusting the CSS for the files individually.

**Comment by maop** [comment]
> For those who are still interested, I came across this which includes the light/dark switch from previous commits by Mokytis => https://gitlab.com/mokytis/hello-friend-ng
> I find git cloning this easier than adjusting the CSS for the files individually.

That repo is 1yr old, you are better using this repo with the commit before @rhazdon made the change: 79d0488

**Comment by rhazdon** [comment]
Hi @folks, 

thank you very much for your discussion. 

Well... I have added the toggle again. But I have changed something about it a little. 

The toggle is now optional. You can switch it on with the option `enableThemeToggle = true`. Then the theme toggle is back on. The theme toggle works in such a way that it always respects the settings of the operating system first. The default is "light". If the theme toggle is allowed, the user's setting is given higher priority. 

For those who want to take a closer look: a64d27b8fcaa2b63545a4be60dd330614e170bbc

**Comment by maop** [comment]
Thanks @rhazdon , is easier to force Dark now... Still i would love if you could add a themePriority option in the config so we can choose what theme we prefer _our_ blogs to use first, i'm all in with the "respect the user preferences", but also, and after all, it is _my_ blog and i would like to reflect my personal preferences in it too

So, answering the original question: My solution was to add a line at the end of assets/js/main.js with the following:

```document.documentElement.setAttribute("data-theme", "dark");``` 

This way it stays Dark.

If anyone knows a better way to force Dark and still let the user chose Light if preferred please let me know.

**Comment by TheGroundZero** [comment]
Where's the toggle button supposed to appear?
I can't see it on my site.

**Comment by undergroundwires** [comment]
Great news! 🥳

> If anyone knows a better way to force Dark and still let the user chose Light if preferred please let me know.

Also looking for this. Actually, more like just enforcing the dark theme and do not really care about the theme switch.

**Comment by aghwotu** [comment]
To get the toggle button back, I reset the commit to the commit just before the toggle button was removed with:

```bash
git reset 8035db5 --hard
```

Please be cautious.

**Comment by d3vilbug** [comment]
Yes, there is one way to force a dark theme is to change the light theme method in `_main.css`

Original method
```
[data-theme=light] & {
  background-color: $light-background;
  color: $light-color;
}
```


Modified method

```
  [data-theme=light] & {
    background-color: $dark-background;
    color: $dark-color;
  }
```
