### ISSUE TITLE
hugo version 0.55.0 

### ISSUE THREAD

**Issue by tmac33** [rhazdon/hugo-theme-hello-friend-ng#27]
when i run this template in hugo 0.55.5 , it comes error like this:
error: failed to transform resource: TOCSS: failed to transform "scss/main.scss" (text/x-scss): this feature is not available in your current Hugo version

when i change the hugo version to 0.55.0, this error is still have.

**Comment by tmac33** [comment]
so what's the right hugo version this template relay on?

**Comment by codgician** [comment]
You need `hugo-extended` for this theme.

**Comment by tmac33** [comment]
> You need `hugo-extended` for this theme.

wonderful.it worked!! thank you
