### ISSUE TITLE
QUESTION Dark/Light theme switch

### ISSUE THREAD

**Issue by MayMeow** [rhazdon/hugo-theme-hello-friend-ng#278]
there is no more manual theme switch (dark/light?). Only way now it is by switching theme on your browser?

**Comment by mondragonfx** [comment]
I am also wondering if the dark/light switch was removed in favor of the system preference. This is what attracted me to the theme.

**Comment by undergroundwires** [comment]
See #253 for same discussion, no input from @rhazdon yet

**Comment by rhazdon** [comment]
Hey folks, I will close this issue because it's a duplicate to https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/253.
