### ISSUE TITLE
Tags pages don't work

### ISSUE THREAD

**Issue by lukesalamone** [rhazdon/hugo-theme-hello-friend-ng#282]
I'm using this theme for my blog: https://lukesalamone.github.io. However, none of the tags pages are working. I see they are working on the demo. Is there a switch I need to enable in my toml? My `config.toml` is here:

https://gist.github.com/lukesalamone/232e55b627b5fe8af549efb7f519b812

**Comment by aghwotu** [comment]
Hello there. 

I am using this theme as well and I noticed that on your blog you have a button to toggle dark and light mode.

Can you tell me how you did it?
When I added the ```enableThemeToggle``` it didn't show the button.
```bash
enableThemeToggle = false
```

Thank you for your time.

**Comment by rhazdon** [comment]
Hi @aghwotu:

Did you placed the parameter on the right place? `enableThemeToggle` has to be placed in the `[params]` area. :) 

```
[params]
    enableThemeToggle = true
```

**Comment by aghwotu** [comment]
@rhazdon I have done it now.
The toggle button is now showing.
Thank you so much.

**Comment by lukesalamone** [comment]
@rhazdon can you re-open this issue? It has nothing to do with theme toggle.

**Comment by rhazdon** [comment]
Please attach your config to the issue.

**Comment by lukesalamone** [comment]
https://gist.github.com/lukesalamone/232e55b627b5fe8af549efb7f519b812

**Comment by lukesalamone** [comment]
Fixed the issue. My list.html had been commented out.
