### ISSUE TITLE
Fonts url not configured correctly when using a baseURL with path

### ISSUE THREAD

**Issue by UKnowWhoIm** [rhazdon/hugo-theme-hello-friend-ng#291]
I'm deploying this theme for in github pages project site, so the baseURL would be `https://xxx.github.io/repo`

The url for fonts would be `https://xxx.github.io/fonts` instead of `https://xxx.github.io/repo/fonts`

Looking at the assets/scss/_fonts.scss file,
```
@font-face {
 ...
  src: url("../fonts/Inter-UI-Italic.woff2") format("woff2"),
       url("../fonts/Inter-UI-Italic.woff") format("woff");
}
```

Shouldn't the url be `fonts/` instead of `../fonts/`?

See: 
- https://discourse.gohugo.io/t/absurl-function-strips-path-when-using-baseurl-flag/5925
- https://github.com/gohugoio/hugo/issues/8078

**Comment by Aliencoder-75** [comment]
@UKnowWhoIm I'm facing the same issue on every single link on the page. But it makes it hard to change every link to . . / its respective locations. Is there a better way to fix the links as well as permalink links in the posts.

**Comment by rhazdon** [comment]
Fixed with https://github.com/rhazdon/hugo-theme-hello-friend-ng/commit/51e697bea7eb265c5b6bc532636bb4c707a84173
