### ISSUE TITLE
Custom PrimsJS SCSS not working properly

### ISSUE THREAD

**Issue by relgisri** [rhazdon/hugo-theme-hello-friend-ng#293]
Hey

I wanted to use a "custom" PrismJS Theme to better fit page design.
To use that I overwrote the _prism.scss file which is located in root path of my page under
$HUGO_PAGE_PATH/assets/scss/_prism.scss
There I removed everything and added this design: https://github.com/PrismJS/prism-themes/blob/master/themes/prism-nord.css

This works so far, because I can see the clear difference after applying the change.
Unfortunately the site somehow overwrites the background-color property for code-blocks when I add a valid programming language to the codeblock.

### Current behavior:

content/posts/this-is-not-working.md
```md
## Test

\```python
print("Hello, World!")
\```
```

![not_working](https://user-images.githubusercontent.com/31743102/115049266-d2b3f400-9eda-11eb-8e3f-c7b2a87be8f1.PNG)

### Expected bevahoir:
except the not working color of the development language:

```md

## Test

\```awhfoawf
print("Hello, World!")
\```
```

![semi_working](https://user-images.githubusercontent.com/31743102/115049748-5837a400-9edb-11eb-97a8-cfac9fe8d943.PNG)

___

By looking at the page source I can see that it somehow generates and adds a background-color property to the codeblock instead of keeping it to "none" as configured in the SCSS.

![page_source](https://user-images.githubusercontent.com/31743102/115050168-c5e3d000-9edb-11eb-9c8e-c2177e2c0a09.PNG)

I am not able to find this color "#272822" anywhere in my project path, therefore I am a bit surprised on where it comes from.
Do you have any clue on what is happening?

**Comment by WexCore** [comment]
Took me a while to figure it out. 
Just add `PygmentsCodeFences = false` to your config file to fix that.

**Comment by WexCore** [comment]
Using `PygmentsCodeFences = false` in the config file fixed that for me.

**Comment by relgisri** [comment]
@WexCore Wow that worked for me.

> PygmentsCodeFences = false
PygmentsStyle = ""

I initially commented both blocks (and after that deactivated one block at a time) but just commenting them doesn't seem to help.
Does anyone can maybe explain on what is going on with those both settings and why just commenting them didn't help?
