### ISSUE TITLE
How to change the text color in the mainpage?

### ISSUE THREAD

**Issue by kevinlee325** [rhazdon/hugo-theme-hello-friend-ng#294]
I set the background from an imge, whose colors are mainly dark. I want to change the text color to white or red. What should I do?

**Comment by rhazdon** [comment]
You ca customize the colors with css. Write a bit css, put it into your style folder and add this to your config. 
https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/exampleSite/config.toml#L96
