### ISSUE TITLE
How to display Text side by side

### ISSUE THREAD

**Issue by scanscanpan** [rhazdon/hugo-theme-hello-friend-ng#295]
Hi,
Thank you for you wonderful theme. 

What would be the best way to achieve side by side view of text on a single page.

Like so:
https://www.homeandlearn.co.uk/WD/images/css_poss/float_cols_browser.gif

Not as table view with borders, just side by text view within the theme.

**Comment by rhazdon** [comment]
Hi @scanscanpan,

thank you. You could play around with some css to achieve this. Check out this page: https://www.w3schools.com/howto/howto_css_two_columns.asp.
