### ISSUE TITLE
Code highlighting is not working

### ISSUE THREAD

**Issue by aledoux45** [rhazdon/hugo-theme-hello-friend-ng#307]
I tried almost every combination to get the code highlighting to work but it still shows the code as plain text...

**config.toml**
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

**my_post.md**
```python
import numpy as np

def foo(arg1, arg2):
  return True
```

Which displays like this on my site:
<img width="247" alt="Screen Shot 2021-06-15 at 8 04 03 PM" src="https://user-images.githubusercontent.com/9044722/122138507-e1545400-ce14-11eb-9008-5413564d2df8.png">

What am I missing?

**Comment by n0leptr** [comment]
@aledoux45 

Are you doing a 4 space indent on the whole block?:

    import numpy as np
    
    def foo(arg1, arg2):
      return True

Have you tried encasing the entire block in triple backtick ?:

```python
import numpy as np

def foo(arg1, arg2):
  return True
```

**Comment by rhazdon** [comment]
Hey @aledoux45: 

Did you tried it with removing this lines? 

```
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"
```

Should work out of the box... This theme is using prismjs mainly for code highlighting. For pygments the [Hugo docs](https://gohugo.io/content-management/syntax-highlighting/) could help. :)

**Comment by aledoux45** [comment]
Hi @rhazdon ,
Yes I tried removing these lines. I did not have them in the code initially and thought this could be the answer why the code highlighting was not working... But it still doesn't :/
I must have commented out an important parameter or script in the HTML.

**Comment by aledoux45** [comment]
@rhazdon I found the answer why: I was using "markup: pandoc" in the front matter (to display some equations written in Latex) and this line was messing up with the code highlighting.
I'm now using "markup: mmark" and katex to display equations and the code highlighting works :).
