### ISSUE TITLE
Favicon not showing?

### ISSUE THREAD

**Issue by benlc** [rhazdon/hugo-theme-hello-friend-ng#31]
I added my favicons as instructed in the README, yet they don't seem to appear nor locally or after a deploy.
<img width="297" alt="Screen Shot 2019-05-22 at 11 22 52 AM" src="https://user-images.githubusercontent.com/1082345/58194902-ff761700-7c83-11e9-86c7-f8d76bdf398b.png">

**Comment by rhazdon** [comment]
Hi @benlc,

are there some logs in your console?

**Comment by benlc** [comment]
Hey @Rhazdon, I didn't have any log. It seems like the favicons ended up showing up today. Not sure if that was a caching issue or what but I tried incognito session before that without success.
Anyway, I'll close for now.
