### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ghost** [rhazdon/hugo-theme-hello-friend-ng#315]
There are broken links everywhere starting from the navigation menu to link to every single post. Even after changing BaseURL form "https://example.com" to "localhost" still, every link leads to 404 page not found error. Is there any other way to fix this URL issue

**Comment by abyss** [comment]
@rhazdon You can close this ticket. User deleted their GitHub account - I think it's not an issue anymore ;)

**Comment by rhazdon** [comment]
@abyss: Great... :D
