### ISSUE TITLE
Dark mode (switch) is missing from the navbar menu

### ISSUE THREAD

**Issue by warifp** [rhazdon/hugo-theme-hello-friend-ng#321]
![image](https://user-images.githubusercontent.com/28912230/128583278-9f394ac2-4514-431d-899f-d4dd7e753ca8.png)

**Comment by abyss** [comment]
Under [params] in your config, you need "enableThemeToggle = true" for the Theme Toggle to appear.

**Comment by warifp** [comment]
Thank!
