### ISSUE TITLE
Does this theme support search function?

### ISSUE THREAD

**Issue by moweiraul** [rhazdon/hugo-theme-hello-friend-ng#327]
When there are more and more blogs, the search function becomes very important.

**Comment by HacDan** [comment]
Not directly, but Hugo along with some client-side javascript like [lunr.js](https://lunrjs.com/) should net you the functionality that you're looking for. 

This article here [Hugo Lunr](https://palant.info/2020/06/04/the-easier-way-to-use-lunr-search-with-hugo/) may be of use to you as well, as the official Hugo documentation isn't that great on integrating lunr.js into your blog.
