### ISSUE TITLE
Pygment highlighting style overriden

### ISSUE THREAD

**Issue by pmorelli92** [rhazdon/hugo-theme-hello-friend-ng#329]
Hi! 

I am using a fork of this theme but I could also reproduce the issue without my modifications.

You can see the video here: https://streamable.com/xf1io9

My config.toml is the following

```
PygmentsCodeFences=true
PygmentsStyle = "fruity"
```

And as you can see on the video the page is rendered with the [`fruity` style ](https://help.farbox.com/pygments.html) and then it gets overriden.

**Comment by HacDan** [comment]
This looks like there are two syntax highlighters competing here. One is Pygments and the other is Prism.js. Prism.js is set to monokai. Pygments is respecting the configuration, whereas Prism.js is not. 

I'm digging a bit deeper to see if this could be an easy fix instead doing something drastic.
