### ISSUE TITLE
Question - Blog post list like original Hello friend theme

### ISSUE THREAD

**Issue by mvdbent** [rhazdon/hugo-theme-hello-friend-ng#340]
have a question, I really like the blog post year overview. however, can I still make a page with the list like in the original Hello Friend Theme?

can I add links to the posts (blog) on the home page like in the theme Hermit?

maybe I miss read the documents but I can't find the options.

thnx

**Comment by rhazdon** [comment]
Hey @mvdbent, unfortunately, this is not possible. :D 
But I'm very thankful to hear that you like the theme. :)
