### ISSUE TITLE
Link to pdf

### ISSUE THREAD

**Issue by MrAntooo** [rhazdon/hugo-theme-hello-friend-ng#344]
How can I create a link to a PDF stored within the project?

**Comment by uGr0x** [comment]
https://www.markdownguide.org/basic-syntax/#links

If you store your PDF under `/static` you can just reference it by `Here's the document: [example.pdf](/example.pdf)` where `example.pdf` in the square brackets is the name, displayed on your site, so you can change this text to what you want.
