### ISSUE TITLE
meta theme-color is added twice

### ISSUE THREAD

**Issue by dherbst** [rhazdon/hugo-theme-hello-friend-ng#358]
The `meta` tag `theme-color` is added twice to the html:

```
find . -type f -exec grep theme-color \{\} \; -print
    <meta name="theme-color" content="{{.Site.Params.favicon.theme}}">
./layouts/partials/favicons.html
<meta name="theme-color" content="{{ .Site.Params.themeColor }}" />
./layouts/partials/head.html
```

Removing the one from `favicons.html` fixes so it is only added from `head.html`.

**Comment by NaincyKumariKnoldus** [comment]
Hey @dherbst Can I solve this please?

**Comment by dherbst** [comment]
@NaincyKumariKnoldus I already pushed the PR up in #359

**Comment by NaincyKumariKnoldus** [comment]
okaay @dherbst

**Comment by rhazdon** [comment]
Hi! :) Thank you very much for your help. :) 
The pr is merged. :)
