### ISSUE TITLE
Posts menu redirects to different link on Demo as seen on Hugo website.

### ISSUE THREAD

**Issue by chshbh** [rhazdon/hugo-theme-hello-friend-ng#36]
I was looking through [this](https://themes.gohugo.io//theme/hugo-theme-hello-friend-ng/) demo. When I click on the Posts menu, It first directs to 
https://themes.gohugo.io/theme/hugo-theme-hello-friend-ng/posts/ and then redirects to https://themes.gohugo.io//theme/hugo-theme-hello-friend-ng/post/. I hope its not breaking something.

**Comment by rhazdon** [comment]
Hi @chshbh,

thank you for your report. I checked the issue but it is only related with the netlify deployment if the exampleSite. So.. nothing to do here. :)
