### ISSUE TITLE
Is it possible to display tags under the title of posts?

### ISSUE THREAD

**Issue by uvicorn** [rhazdon/hugo-theme-hello-friend-ng#361]
Now:

![изображение](https://user-images.githubusercontent.com/59787538/151870508-60f1e02b-4a23-414e-9eb9-3ea6c8660522.png)
I want it to look something like this:

![изображение](https://user-images.githubusercontent.com/59787538/151871616-d59a2f27-22a7-4b13-a0aa-9c26e4eec2c2.png)

**Comment by n0sandb0x** [comment]
Hi @uvicorn hope you are well, Can you please tell how did you added tags under the title of posts?. I'm also facing the same problem and only Date is appearing. 

![tags](https://github.com/rhazdon/hugo-theme-hello-friend-ng/assets/60497235/2a8ae1a4-ade9-4eb9-abfd-4ef98a00afd0)


Is it possible to get everything like tags and description as well just like from https://github.com/panr/hugo-theme-hello-friend ?

![all](https://github.com/rhazdon/hugo-theme-hello-friend-ng/assets/60497235/af304105-681e-47c4-b6bf-174dd6ce2805)
