### ISSUE TITLE
[Question] Change start page to show posts list

### ISSUE THREAD

**Issue by michael-schramm** [rhazdon/hugo-theme-hello-friend-ng#379]
Hi,
thank you very much for this great theme.
I managed to make a few changes for SEO optimization, like unique and custom title and meta description, but I just can not figure out how to create a post list for the front page, just like in the original hello-friend theme.
I would like the main page to show the post list just like it is currently been shown under /posts/.

Thanks!

**Comment by MayMeow** [comment]
check `./themes/hello-friend-ng/layouts/_default/single.html` but i think you will need to filter you want to list only posts https://gohugo.io/templates/lists/ and https://gohugo.io/functions/where/

Homepate is located `./themes/hello-friend-ng/layouts/index.html`

**Comment by michael-schramm** [comment]
It worked!
Thank you very much!
:-)
I copied the list.html, renamed it to index.html and made a few changes using the filter.
