### ISSUE TITLE
Probably the dumbest question/request ever: landingpage

### ISSUE THREAD

**Issue by erno1978** [rhazdon/hugo-theme-hello-friend-ng#383]
My web-building-skills are a bit rusty (I'm from the HTML-in-notepad-age), but I'm searching for hours now how to change the landing page of the website. I tried various settings (with baseURL etc), but all I want is a specific page to be the first when someone enters "https://www.oursite.com". Right now it's showing a sort of one-liner what the page is. But we want to go to https://www.oursite.com/about instead.

Is this possible without going through a lot of manual configurations? And even if not: can you give a nudge in the right direction how to change it manually?

**Comment by TheGroundZero** [comment]
See `layouts/index.html`
