### ISSUE TITLE
How to enable discuss? :(

### ISSUE THREAD

**Issue by hervyqa** [rhazdon/hugo-theme-hello-friend-ng#39]
How to enable Discuss, I've set it up in config.yaml, but there is no change

**Comment by rhazdon** [comment]
Hi @hervyqa,

you just need to add the config described in the README usually.

Be aware that the disqus integration only works from the right origin. Locally it won't work - you have to deploy it.

**Comment by hervyqa** [comment]
I have added disqus from external partial.  I've fixed this.
