### ISSUE TITLE
[Feature Request] Add Cloudflare Web Analytics Support

### ISSUE THREAD

**Issue by L1ghtn1ng** [rhazdon/hugo-theme-hello-friend-ng#394]
This is what the docs say where to put it "Add the JS Snippet below before the ending body tag on any of your HTML pages."

`<script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "add-token-here"}'></script>`

**Comment by georgioupanayiotis** [comment]
Hello @L1ghtn1ng can you please assign this to me?

**Comment by L1ghtn1ng** [comment]
@georgioupanayiotis I do not have the permissions to do that

**Comment by L1ghtn1ng** [comment]
@georgioupanayiotis Any updates on this?

**Comment by L1ghtn1ng** [comment]
Have forked this and added it myself with a few other custom changes I waned
