### ISSUE TITLE
Add possibility to override cloudflare hosted css

### ISSUE THREAD

**Issue by shibumi** [rhazdon/hugo-theme-hello-friend-ng#41]
Hello,
I take care about security and I have implemented a strong default CSP for my website.
Your theme is sideloading css and some javascript via cloudflare from this destination:

https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.2.1/css/flag-icon.min.css

It would be nice, if you could add an option to provide the css file locally.

**Comment by shibumi** [comment]
sounds great

**Comment by AdmiralNemo** [comment]
Any update on this?  I don't like that Firefox enables "Enhanced Tracking Protection" on my site because of the third-party cookies Cloudflare sends with this CSS file.

**Comment by shibumi** [comment]
I just switched to the hermit theme.. it's faster, too.

**Comment by rhazdon** [comment]
I don't think that including the hole flag-icons thing into this project is a good idea. So well, I will close the issue. Hermit is awesome, too. :)

**Comment by satyamkapoor** [comment]
Hi @rhazdon, thanks a lot for the theme. It's great. Was closely inspecting the theme for setting up a cookie policy and found the cloudflare cdn hosted flags stylesheet. I'm curious where is this being used in the theme? Will it be okay if I just remove it?

**Comment by rhazdon** [comment]
Hi @satyamkapoor, the flags are used for the i18n. You can setup single posts in multiple language and the reader is able to switch the language through the flags. :)

**Comment by satyamkapoor** [comment]
Thanks for the explanation. Since I'm going to write my blogs just in English perhaps I can get this part off?
