### ISSUE TITLE
Remove Cloudflare CDN for privacy reasons

### ISSUE THREAD

**Issue by br4yd** [rhazdon/hugo-theme-hello-friend-ng#418]
Could we please remove Cloudflare CDN for privacy reasons? It's only used for to load one CSS file named "flag-icon.min.css".

This could easily be embedded into the project code and loaded locally. Changing this would not send or fetch any data to or from Cloudflare anymore, which would make it easier (and safer) for users to use, because as soon as you connect to any third party like the Cloudflare CDN you will need a legal text for that in your privacy policy in Germany.

Thank you in advance!

**Comment by Sabering1** [comment]
i agree cloudflare is spyware, but this project seems kinda dead so i dont think it will get seen or removed soon

**Comment by rhazdon** [comment]
I don't think it's dead. ;D

**Comment by rhazdon** [comment]
There you go! :) 

2e90fec04f82a93a02f3d1e71e46ac9bbfa693c3

**Comment by br4yd** [comment]
Thank you very much! 🙏
