### ISSUE TITLE
CSS not rendering, because of CORS not enabled error

### ISSUE THREAD

**Issue by 0phoi5** [rhazdon/hugo-theme-hello-friend-ng#423]
Please see https://www.jackcollins.me.uk/ (currently 10th April 2023), specifically the Developer Console.

The site's CSS does not render, because of the following error in console;
"Subresource Integrity: The resource 'https://jackcollins.me.uk/main.fdbf67c1c5b35c383c80cfa6498f36263db3d5b9c48a7b6b50bc7e7249d8e12c.css' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced."

The same error occurs if I replace the baseURL with https://jackcollins.me.uk/ or https://www.jackcollins.me.uk/ or just /.

The site renders fine locally (hugo serve).

Note that the site is hosted via AWS Amplify, and I have https://jackcollins.me.uk forwarding to https://www.jackcollins.me.uk

**Comment by rhazdon** [comment]
Hey @0phoi5  :) 

What's your value for `baseURL` in your `config.toml`?

**Comment by 0phoi5** [comment]
If it helps, here is the current code; https://github.com/0phoi5/jackcollins.me.uk

**Comment by 0phoi5** [comment]
It seems this may cover the solution, but would require an update to the Template's link ref; https://codinginthetrenches.com/2021/06/26/cross-origin-headers-cors-aws-s3-and-aws-cloudfront/

**Comment by 0phoi5** [comment]
Created https://github.com/rhazdon/hugo-theme-hello-friend-ng/pull/424
