### ISSUE TITLE
Is it possible to resize and add a border to images?

### ISSUE THREAD

**Issue by A-J-A** [rhazdon/hugo-theme-hello-friend-ng#426]
I'm creating a blog post and including snips from an iPhone, can I use any inline formatting to size the images and add a border?

**Comment by FluffMe** [comment]
Hi,

* If you want to change how all of the images in all of the posts look like -- you can just override the css rules with your custom CSS. This should be fairly straightforward.
* If you want to change just some of the images, you can either create a new CSS class and apply it to these images via a new shortcode or with a [Markdown Render Hook](https://gohugo.io/templates/render-hooks/) 

Hope this helps!

**Comment by A-J-A** [comment]
thank you
