### ISSUE TITLE
Social icons for Tiktok, X (instead of twitter) and Threads

### ISSUE THREAD

**Issue by yanbodon** [rhazdon/hugo-theme-hello-friend-ng#465]
Hi, I'm currently building a content creator website and I found out that there's a few missing social media websites. It would be nice, if Tiktok and Threads could be added as well as Twitter icon updated to X.

**Comment by egelmex** [comment]
Can this ticket now be closed?

**Comment by rhazdon** [comment]
Yes, the icons are in! :)
