### ISSUE TITLE
MIT License Violation

### ISSUE THREAD

**Issue by balibebas** [rhazdon/hugo-theme-hello-friend-ng#47]
You state your theme was heavily inspired, but that actually doesn't satisfy the terms of the MIT License, which requires you to add the copyright notice from the original theme author(s):

https://github.com/panr/hugo-theme-hello-friend/blob/master/LICENSE.md

If you combined two works with different licenses, you will need to satisfy both assuming they're compatible.

Sorry you weren't informed when you submitted your theme to Hugo. They don't seem to pay much attention to intellectual property laws.

You may find this a valuable read: https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html

Best of luck.

**Comment by rhazdon** [comment]
Two different licenses? This one is under MIT and the both from where I was inspired by are under MIT license. 

Where is the violation exactly?

**Comment by balibebas** [comment]
https://writing.kemitchell.com/2016/09/21/MIT-License-Line-by-Line.html#notice-condition

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Looking at your license you're violating the only condition of the license. Didn't you feel at least a little funny when you removed @panr from the license in the first place?

**Comment by rhazdon** [comment]
Not really... Why should I feel funny? 

```
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
```

If this means that the origin copyright owners have to be included as well, fair enough. I wasn't sure about that. I am a developer, not a lawyer. ;)

Do you have an example of how this should look like?

**Comment by rhazdon** [comment]
What's about https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/master/LICENSE.md

**Comment by balibebas** [comment]
I can't comment on how the license should be as I have not thoroughly reviewed the source code. But I can say after looking at your latest changes it's more suitable following your recent changes as it appears to meet the terms stated in the *notice condition* of the MIT.
