### ISSUE TITLE
.Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.135.0. Use .Site.Config.Services.Disqus.Shortname instead

### ISSUE THREAD

**Issue by TheGroundZero** [rhazdon/hugo-theme-hello-friend-ng#484]
Error when building site with Hugo v0.134.0

```
ERROR deprecated: .Site.DisqusShortname was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.135.0. Use .Site.Config.Services.Disqus.Shortname instead
```

https://github.com/rhazdon/hugo-theme-hello-friend-ng/blob/a902dacd8477728158ca181e17a340ea2f36d1ac/layouts/posts/single.html#L125

**Comment by brha8286** [comment]
Valid [workaround](https://github.com/lukeorth/poison/pull/194/files)

**Comment by TheGroundZero** [comment]
> Valid [workaround](https://github.com/lukeorth/poison/pull/194/files)

You need to both change those references as well as the config file
