### ISSUE TITLE
Can we have 2 separate post list pages for 2 different languages

### ISSUE THREAD

**Issue by prashantbhardwaj** [rhazdon/hugo-theme-hello-friend-ng#50]
This issue is explained in detail in following question - https://stackoverflow.com/questions/57486164/hugo-is-not-creating-post-list-page-for-language-other-than-english

**Comment by rhazdon** [comment]
Hmm... I think yes, but you should check out the hugo documentation for that. With hugo you are able to create quite complex sites.
