### ISSUE TITLE
Should prism.js reference removed from the README?

### ISSUE THREAD

**Issue by returntrip** [rhazdon/hugo-theme-hello-friend-ng#52]
I see that it was removed on this commit https://github.com/rhazdon/hugo-theme-hello-friend-ng/pull/6

**Comment by rhazdon** [comment]
But it was Adel again in https://github.com/rhazdon/hugo-theme-hello-friend-ng/commit/62747aae63fccdc36f123d7c7980b371c1ab15db

:)

**Comment by returntrip** [comment]
I got fooled by the issue and the fact that code searches do not work in forked repositories :)
