### ISSUE TITLE
Can we add support for disqus? Thanks!

### ISSUE THREAD

**Issue by davidfeng88** [rhazdon/hugo-theme-hello-friend-ng#53]
Migrated my site from hermit to hugo-theme-hello-friend-ng. Like everything but miss the disqus support. Thanks a lot!

**Comment by returntrip** [comment]
Have not tried myself but look here: https://github.com/rhazdon/hugo-theme-hello-friend-ng/issues/39#issuecomment-511731672

I think the setting is: `diaqusShortname = "your_id"`

**Comment by davidfeng88** [comment]
I have the [setup](https://github.com/davidfeng88/davidfeng.us/blob/bee88758d160531e52e7729c754a995e18efc2e0/config.toml#L11), and it was working before with hermit theme. However, it's not working now and I do not know what's going on...

**Comment by davidfeng88** [comment]
Figured it out myself: need to specify `comments: true` in the markdown file.

**Comment by ameenpv** [comment]
> Figured it out myself: need to specify `comments: true` in the front matter of the markdown file.

Thanks. This solved the issue. Try using the correct format according to your front matter format:
https://gohugo.io/content-management/front-matter/
