### ISSUE TITLE
Help needed: code blocks are centered when using asciidoc

### ISSUE THREAD

**Issue by returntrip** [rhazdon/hugo-theme-hello-friend-ng#55]
When I use this wonderful theme with asciidoc documents, my code blocks are centered instead of being aligned to the left. Could you help me troubleshoot the issue?

I have tested with a different theme and it works there, so I am assuming there is some incompatibility found in this specific theme.

Here is an example of the issue:
![asciidoc_layout](https://user-images.githubusercontent.com/14056122/63459467-e03e7f80-c454-11e9-9a04-fd4864a901c9.png)

**Comment by rhazdon** [comment]
With the update of prism js the issue is solved. :)
