### ISSUE TITLE
Unable to set home url directly to posts

### ISSUE THREAD

**Issue by wojciehm** [rhazdon/hugo-theme-hello-friend-ng#58]
Hi.

I'd like to configure the theme following: when somebody enters my website I'd like to display posts and not main page and the user has to click manually to posts.

How can I do it?

**Comment by rhazdon** [comment]
This is one thing why I actually made this theme. :D 

You could either redirect your visitors or you could check out https://themes.gohugo.io/hugo-theme-hello-friend/.
