### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by 0v3rt1r3d** [rhazdon/hugo-theme-hello-friend-ng#60]
Hello, friend! You made a beautiful theme! I want to use it, but I met several problems in my way.
1. I would like to have two languages: English and Russian, but there is no russian flag in the interface, could add it? Or maybe there is a way to configure the theme to use language names instead of pictures?
2. The second problem may not be referenced with your theme, but could not configure hugo to show the site in another default language, russian. I have read the manual https://gohugo.io/content-management/multilingual/#multilingual-themes-support, but this doesn't work for me. Could you show me an example of your theme with multilanguage support?

Hugo version is `0.57.2` and the config in `.toml`:
```
baseurl = "/"
languageCode = "en-us"
theme = "hello-friend-ng"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  keywords = "key, words"
  images = [""]

  defaultContentLanguage = "ru"
  contentTypeName = "posts"

[languages]
  [languages.ru]
    weight = 1
    languageName = "Русский"
    title = "Блог"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Показать ещё"
    readMore = "Читать полностью"
    readOtherPosts = "Читать другие статейки"

    [languages.ru.params.logo]
      logoText = "logo text"

    [languages.ru.menu]
      [[languages.ru.menu.main]]
        identifier = "about"
        name = "О блоге"
        url = "/about"
      [[languages.ru.menu.main]]
        identifier = "showcase"
        name = "Лента"
        url = "/posts"

  [languages.en]
    weight = 0
    languageName = "English"
    title = "my blog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "logo"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Posts"
        url = "/posts"
```

**Comment by rhazdon** [comment]
Hi @0v3rt1r3d, 

I would love to see a pull request with the Russian flag. Do not forget the i18n configuration, too. :)

Regarding your second question: Check out my own blog repo: https://github.com/rhazdon/homepage. 
But I think that the issue in your config is the spelling of `defaultContentLanguage`. As I think it should be `DefaultContentLanguage`.
