### ISSUE TITLE
Looking for more documentation

### ISSUE THREAD

**Issue by rjgonza** [rhazdon/hugo-theme-hello-friend-ng#65]
Just want to start off with saying that I love this theme! I was starting to leverage it a bit more and came across the social params and thought about what else I don't know about. Should I be looking at the themes it was forked from or is there another area for documentation? This is my first try with hugo and so far it's been awesome.

**Comment by Jarzamendia** [comment]
Hello dude, I'm also strugle with the lack of documentation. I'm end find the site example in the repo, get the link: https://github.com/rhazdon/hugo-theme-hello-friend-ng/tree/master/exampleSite

I'm planning make a PR with what I learned when finish a personal blog.

By the way, this theme is awesome!

**Comment by rjgonza** [comment]
> 
> 
> Hello dude, I'm also strugle with the lack of documentation. I'm end find the site example in the repo, get the link: https://github.com/rhazdon/hugo-theme-hello-friend-ng/tree/master/exampleSite
> 
> I'm planning make a PR with what I learned when finish a personal blog.
> 
> By the way, this theme is awesome!

100% agree, love this theme. Looking forward to the post, hopefully I can add something there as well.

**Comment by rjgonza** [comment]
Was there a commit for this?
