### ISSUE TITLE
Social icons

### ISSUE THREAD

**Issue by JosephBak** [rhazdon/hugo-theme-hello-friend-ng#69]
Hello,
Does anyone know how to add social icons for use?
I would like to use Kaggle icon.

For now, I think codepen, facebook, gitbook, github, gitlab, instagram, linkedin, slack, twitter, youtube, email, telegram, and stackoverflow work. Is that other social icons that work?

**Comment by rhazdon** [comment]
Hi @JosephBak, I have added the Kaggle icon and also some documentation on the README. :)
