### ISSUE TITLE
disable " READ OTHER POSTS"

### ISSUE THREAD

**Issue by camscofie** [rhazdon/hugo-theme-hello-friend-ng#71]
Can we somehow disable the READ-OTHER-POSTS function when we look at the posts?

**Comment by JPYamamoto** [comment]
I just implemented this in my last pull request (https://github.com/rhazdon/hugo-theme-hello-friend-ng/pull/73). Let me know if that works as you expected, and let's wait for it to be merged.

**Comment by rhazdon** [comment]
Merged. :)
