### ISSUE TITLE
What's comments support for this theme?

### ISSUE THREAD

**Issue by Sailfishc** [rhazdon/hugo-theme-hello-friend-ng#79]
i config disqusShortname = "disqusID" in config.toml，but my blog can't display  Disqus comments,this  
theme is not support comments?

**Comment by rhazdon** [comment]
Hi @Sailfishc,

how did you tried it? Keep in mind that disqus needs a valid origin. Running `hugo server` on your machine can not work.

**Comment by Sailfishc** [comment]
Hi @rhazdon 
yes. my local machine is not work,but my production site is same. the site : https://blog.sailfishc.cn/

**Comment by Sailfishc** [comment]
this project is good, do you have a roadmap?

**Comment by rhazdon** [comment]
Not really... :D
