### ISSUE TITLE
Plural / Singular handle for static menu names

### ISSUE THREAD

**Issue by sam5558** [rhazdon/hugo-theme-hello-friend-ng#80]
Hi @rhazdon ,
Great template you have here. 
I would like a bit of help concerning menu names. 
Let's say i choose the following menu names : 
![image](https://user-images.githubusercontent.com/26897744/69233506-50ac8800-0b8d-11ea-93b5-6ce004faa7c3.png)
What i expect is to have the same names in the pages content, the thing is either gohugo or the template adds a "s" or "es" for plural.
![image](https://user-images.githubusercontent.com/26897744/69233627-89e4f800-0b8d-11ea-8ac9-e5f67fb846cb.png)

I can't find in the config.toml where i should edit this option.
I'm pretty much facing the same issue unless i use a name already in plural form.

Any help ? 
Thanks

**Comment by matiasandina** [comment]
I experienced the same. Changing the folder and name structure partially solves the issue, but it would be nice to have consistent 
```
|-- content
|---- Singular
|-------- singular.md
```

I get the `singulars` page and need to access as `./singular/singular`

```
|-- content
|---- Singular
|-------- index.md
```

I don't get the plural added and lands directly on /singular. In my case I didn't want to have a menu landing page like the one in `posts`

**Comment by rhazdon** [comment]
Hi, well, in the `list.html` of the _default templates the `<h1>` tag looks like the following: 
```
<h1>{{ .Title }}</h1>
```

So I think this is a hugo thing, not related to the theme.

My folder structure looks like:

```
|-- content
|---- my-topic
|------ index.en.md
|------ index.de.md
```

With this folder structure I did not notices any issues with unexpected pluralization.

**Comment by rhazdon** [comment]
https://github.com/rhazdon/hugo-theme-hello-friend-ng/commit/9f3c15b70e61cf8eb466aa96a34250a27c3ac7b0 should fix the issues. :)

**Comment by sam5558** [comment]
Hello @rhazdon,
Thank you for the fix.
I've downloaded the latest version of the theme, it seems to be working great. :+1: 
Cheers
