### ISSUE TITLE
Icon podcast

### ISSUE THREAD

**Issue by victorsnk** [rhazdon/hugo-theme-hello-friend-ng#88]
How can I put this icon: https://simpleicons.org/?q=podcas

**Comment by victorsnk** [comment]
No body can help my?

**Comment by rhazdon** [comment]
Hi @victorsnk, the podcasts icons are now available. `podcasts-apple` and `podcasts-google` are the keys (also documented in the readme).

**Comment by victorsnk** [comment]
Good morning!  

First of all, thank you for the answer.  I had not seen that icon.  many thanks.  On the other hand, is it possible to include the one of the famous platform of free distribution photographs Pixabay?
https://pixabay.com/es/

Thank you very much!
