### ISSUE TITLE
Add theming support for shortcodes

### ISSUE THREAD

**Issue by thedataking** [rhazdon/hugo-theme-hello-friend-ng#89]
I'd like to be able to show different images depending on the currently selected theme (dark|light). I don't see a hugo variable that shows the currently selected theme since it is all done with CSS, so I don't know how hard this is to do, but it would be very helpful to extend theming support to figures and images. Thanks in advance for your consideration and hard work!

**Comment by rhazdon** [comment]
Hi @thedataking, 

this is a great idea, but honestly I do not the time to do this right now. But I would love add your contribution! :)
