### ISSUE TITLE
allow for custom cursor animation durations

### ISSUE THREAD

**Issue by cdanis** [rhazdon/hugo-theme-hello-friend-ng#94]
While 1s is a totally reasonable duration, I think 2s looks a lot calmer.  It'd be nice if this was easy to override from a configuration variable.

**Comment by rhazdon** [comment]
Hi, thanks for working on the theme! :) 

@npjg I have changed the naming of the configuration options

`logoDisabled` -> `logoCursorDisabled`
`logoColor` -> `logoCursorColor`
`logoCursorAnimate` -> `logoCursorAnimate`
