### ISSUE TITLE
Add more Hugo built-in shortcodes

### ISSUE THREAD

**Issue by niladridutt** [rhazdon/hugo-theme-hello-friend-ng#95]
How can I get more hugo built-in shortcodes?

**Comment by FabioBaroni** [comment]
I'm new to Hugo, but shouldn't Hugo shortcodes be included by default in any theme unless they are overriden in some way? Unless you mean create new ones. https://gohugo.io/templates/shortcode-templates/

**Comment by niladridutt** [comment]
No, a lot of the default shortcodes aren't included. Even the figure shortcode doesn't have all the parameters like width and height.

**Comment by FabioBaroni** [comment]
> No, a lot of the default shortcodes aren't included. Even the figure shortcode doesn't have all the parameters like width and height.

well, I don't wanna sound rude, but it sucks. Even the figure shortcode is mentioned in the theme's readme so I assumed it was supported. Then i try it and it doesn't work. Themes should have the main Hugo shortcodes, I don't see the point in removing them. I'll check and see if I can add them by myself. I'm not asking for some fancy custom shortcodes, just the default ones. I'm new to Hugo and having a nice theme is very much appreciated, but I feel like sometimes the way themes are made can be confusing and troublesome for beginners.

**Comment by niladridutt** [comment]
Exactly, the default shortcodes should be included. I see no point in not including them by default, it just makes the job easier.

**Comment by rhazdon** [comment]
I can fully understand your argumentation and see it the same way. I would be very happy about a collaboration from you, if you are interested. Unfortunately I can't promise you until when I will have the shortcodes in, but I will do my best for you. :)

**Comment by rhazdon** [comment]
With the last commit (9ad7b8161b33671bcc3b685b33782221fa7fb26e) I have removed the custom figure so the hugo default one is used now. Also, you are free to use all hugo built in shortcodes you want to. :)
