### ISSUE TITLE
Can't display images in posts

### ISSUE THREAD

**Issue by FabioBaroni** [rhazdon/hugo-theme-hello-friend-ng#96]
Hello, I tried for long time to display an image in a post, but I couldn't figure out how.
I tried using markdown syntax and also the image and figure Hugo shortcodes. It can't load the image, so I'm wondering wether the path is correct or not. I tried to put the image in /static, then I tried /static/img, /static/images/, nothing worked. What did I do wrong? Can you please help me? I also looked at the configuration file and tried to change it. I also tried to put "images: [""] with the path to the image folder in the front matter, but nothing worked.

![](/static/image.jpg)

![](/static/img/image.jpg)

{{< image src="/static/image.jpg" alt="Hello Friend" position="center" style="border-radius: 8px;" >}}

{{< image src="/static/image.jpg" alt="Hello Friend" position="center" style="border-radius: 8px;" >}}

{{< image src="/static/img/image.jpg" alt="Hello Friend" position="center" style="border-radius: 8px;" >}}

{{< image src="/static/images/image.jpg" alt="Hello Friend" position="center" style="border-radius: 8px;" >}}

I hope you can help me.

**Comment by niladridutt** [comment]
You can try moving the images from static to content/images/
Shortcodes for images won't work in static.

**Comment by FabioBaroni** [comment]
I tried what you suggested and apparently it isn't working.
Anyway I thought static was for static files, so even for images. There should be a default configuration and a way to override it, but I can't find it in the documentation.
This may be a simple problem but it's stopping me from progressing. I'm new to Hugo. Not sure if this is something theme specific or Hugo specific. @rhazdon can you help? Thanks

**Comment by FabioBaroni** [comment]
I think I solved the problem, at least my image is showing now.
See here: [https://gohugo.io/content-management/static-files/](https://gohugo.io/content-management/static-files/)
As I said the static folder is used for serving static files (css, js, images) and I thought that I could also create subfolders and reference any file by its relative url, I always developed static websites by myself and not using a static site generator. I found that that during the building process, Hugo moves the content of /static to the root of the site, so I should put the file inside static like this: /static/image.jpg but reference it as /image.jpg. Well is it the only way of embedding local images? Can we change the standard image folder?

**Comment by Ibinola** [comment]
thanks for this! after searching all over the internet. This worked!

**Comment by ashleymavericks** [comment]
Thanks a lot for this, much appreciated!

**Comment by tmcybers** [comment]
> I think I solved the problem, at least my image is showing now. See here: https://gohugo.io/content-management/static-files/ As I said the static folder is used for serving static files (css, js, images) and I thought that I could also create subfolders and reference any file by its relative url, I always developed static websites by myself and not using a static site generator. I found that that during the building process, Hugo moves the content of /static to the root of the site, so I should put the file inside static like this: /static/image.jpg but reference it as /image.jpg. Well is it the only way of embedding local images? Can we change the standard image folder?

you save mi life,man. 3 years after

**Comment by yiskaneto** [comment]
> You can try moving the images from static to content/images/ Shortcodes for images won't work in static.

This actually worked for me. Thanks!
