### ISSUE TITLE
images too big

### ISSUE THREAD

**Issue by FabioBaroni** [rhazdon/hugo-theme-hello-friend-ng#99]
I added some images using the picture shortcode, it's working but they appear too big. It may have to do with the theme. If I specify the size using height and width like indicated here https://gohugo.io/content-management/shortcodes/ but nothing changes. Can I add inline styling or how do I edit the css of the page in Hugo?

**Comment by rhazdon** [comment]
Hi @FabioBaroni, 

did you try both `figure` and `image`?

You can set in inline style to change the size:

```
{{< figure src="/my.png" alt="a pic" position="center" style="height:250px;">}}
{{< image src="/my.png" alt="another pic" style="height:250px;">}}
```
